// Auto-generated by zfb-content. Do not edit by hand.
declare module "zfb-collections" {
  export interface Collections {
    docs: {
      slug: string;
      data: {
        sidebar_position?: number;
        title: string;
      };
    };
    blog: {
      slug: string;
      data: {
        date: string;
        tags?: string[];
        title: string;
      };
    };
  }
  export function getCollection<K extends keyof Collections>(name: K): Collections[K][];
}

declare module "zfb/content" {
  export interface ZfbCollections {
    docs: {
      slug: string;
      data: {
        sidebar_position?: number;
        title: string;
      };
      body: string;
    };
    blog: {
      slug: string;
      data: {
        date: string;
        tags?: string[];
        title: string;
      };
      body: string;
    };
  }
  export function getCollection<K extends keyof ZfbCollections>(name: K): ZfbCollections[K][];
  export function getEntry<K extends keyof ZfbCollections>(
    name: K,
    slug: string,
  ): ZfbCollections[K] | undefined;
}
