export type {
  HeaderNavChildItem,
  HeaderNavItem,
  HeaderRightItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  FrontmatterPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
  BodyFootUtilAreaConfig,
  TagPlacement,
  TagGovernanceMode,
  TagVocabularyEntry,
  MetaTagsConfig,
} from "./settings-types";
import type {
  HeaderNavItem,
  HeaderRightItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  FrontmatterPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
  BodyFootUtilAreaConfig,
  TagPlacement,
  TagGovernanceMode,
  MetaTagsConfig,
  Settings,
} from "./settings-types";

export const settings = {
  colorScheme: "Default Dark",
  colorMode: {
    defaultMode: "dark",
    lightScheme: "Default Light",
    darkScheme: "Default Dark",
    respectPrefersColorScheme: true,
  } satisfies ColorModeConfig as ColorModeConfig | false,
  siteName: "zfb",
  siteDescription:
    "The Rust engine under your content-site framework — router, renderer, content pipeline. Author in TypeScript/JSX, runs as a single binary." as string,
  base: "/",
  trailingSlash: false as boolean,
  minifyHtml: true as boolean,
  noindex: false as boolean,
  editUrl: false as string | false,
  githubUrl: "https://github.com/Takazudo/zudo-front-builder" as string | false,
  siteUrl: "https://zfb.takazudomodular.com" as string,
  metaTags: {
    description: true,
    keywords: false,
    ogImage: "/img/ogp.png",
    ogSiteName: true,
    twitterCard: "summary_large_image",
  } satisfies MetaTagsConfig as MetaTagsConfig,
  docsDir: "src/content/docs",
  defaultLocale: "en" as string,
  locales: {
    ja: { label: "JA", dir: "src/content/docs-ja" },
  } as Record<string, LocaleConfig>,
  mermaid: true,
  sitemap: true,
  docMetainfo: true,
  // IMPORTANT — keep false until the tag route modules exist (pages/docs/tags/
  // index.tsx, [tag].tsx, and locale counterparts). Flipping true without those
  // modules causes /docs/tags and /docs/tags/{tag} links to 404.
  docTags: false,
  tagPlacement: "after-title" as TagPlacement,
  tagGovernance: "off" as TagGovernanceMode,
  tagVocabulary: false as boolean,
  frontmatterPreview: false as FrontmatterPreviewConfig | false,
  llmsTxt: true,
  math: false,
  cjkFriendly: true as boolean,
  onBrokenMarkdownLinks: "warn" as "warn" | "error" | "ignore",
  aiAssistant: false as boolean,
  aiChatDemoMode: false as boolean,
  aiChatAllowedOrigins: [] as string[],
  aiChatGlobalDailyLimit: false as number | false,
  docHistory: true,
  bodyFootUtilArea: false as BodyFootUtilAreaConfig | false,
  designTokenPanel: false as boolean,
  tocMinDepth: 2 as number,
  tocMaxDepth: 4 as number,
  // flat — the pre-zfb site used github-slugger flat heading IDs; "flat"
  // preserves existing #anchor deep links (the scaffold default is
  // "hierarchical"). See issue #877 step 3.
  headingIdStrategy: "flat" as "flat" | "hierarchical",
  sidebarResizer: true as boolean,
  sidebarToggle: true as boolean,
  imageEnlarge: true as boolean,
  dynamicPageTransition: true as boolean,
  htmlPreview: undefined as HtmlPreviewConfig | undefined,
  versions: false as VersionConfig[] | false,
  claudeResources: {
    claudeDir: ".claude",
  } as { claudeDir: string; projectRoot?: string } | false,
  defaultLocaleOnlyPrefixes: [
    "/docs/claude-md/",
    "/docs/claude-skills/",
    "/docs/claude-agents/",
    "/docs/claude-commands/",
  ] as string[],
  footer: {
    links: [
      {
        title: "Docs",
        items: [{ label: "Getting Started", href: "/docs/getting-started" }],
      },
    ],
    copyright: `Copyright © ${new Date().getFullYear()} <a href="https://x.com/Takazudo">Takazudo</a>. Built with <a href="https://takazudomodular.com/pj/zudo-doc">zudo-doc</a>.`,
  } satisfies FooterConfig as FooterConfig | false,
  headerNav: [
    { label: "Getting Started", path: "/docs/getting-started", categoryMatch: "getting-started" },
    { label: "Concepts", path: "/docs/concepts", categoryMatch: "concepts" },
    { label: "Guides", path: "/docs/guides", categoryMatch: "guides" },
    { label: "Reference", path: "/docs/api", categoryMatch: "api" },
    { label: "Architecture", path: "/docs/architecture", categoryMatch: "architecture" },
    { label: "Claude", path: "/docs/claude", categoryMatch: "claude" },
    {
      label: "Markdown Features",
      path: "/docs/markdown-features",
      categoryMatch: "markdown-features",
    },
    { label: "Changelog", path: "/docs/changelog", categoryMatch: "changelog" },
  ] as HeaderNavItem[],
  headerRightItems: [
    { type: "component", component: "github-link" },
    { type: "component", component: "theme-toggle" },
    { type: "component", component: "search" },
    { type: "component", component: "language-switcher" },
  ] as HeaderRightItem[],
  packageOwnedRoutes: true,
} satisfies Settings;
