[package]
name = "zudo-wind"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Owned utility CSS language parser and engine"

[dependencies]
lightningcss = { workspace = true }
globset = { workspace = true }
ignore = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
