/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 410fa0fb3b97aef54752e7c1db00cf6f)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env {
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
