import DefaultLayout from "../layouts/default";

const metrics = [
  { label: "Preview build", value: "Static", detail: "Generated by zfb into dist/" },
  { label: "Gate scope", value: "All paths", detail: "Worker runs before Static Assets" },
  { label: "Audience", value: "Reviewers", detail: "Shared password, no user accounts" },
];

export default function HomePage() {
  return (
    <DefaultLayout title="Overview - Preview Desk" active="overview">
      <section class="page-heading">
        <p class="eyebrow">Protected preview</p>
        <h1>Account portal review packet</h1>
        <p>
          A compact static mini-site for sharing release notes, review status, and launch tasks
          behind a simple Worker password gate.
        </p>
      </section>

      <section class="metric-grid" aria-label="Preview summary">
        {metrics.map((metric) => (
          <article class="metric-card" key={metric.label}>
            <span>{metric.label}</span>
            <strong>{metric.value}</strong>
            <p>{metric.detail}</p>
          </article>
        ))}
      </section>

      <section class="split-layout">
        <div>
          <h2>Review focus</h2>
          <p>
            The current build focuses on navigation clarity, a quieter billing state, and support
            copy for teams that invite external collaborators.
          </p>
        </div>
        <ul class="compact-list">
          <li>Billing card copy is ready for legal review.</li>
          <li>Invite flow states are frozen for this preview.</li>
          <li>Support notes remain editable until launch freeze.</li>
        </ul>
      </section>
    </DefaultLayout>
  );
}
