// Single source of truth for the `_worker.js` wrapper string.
//
// Kept as a plain `.mjs` module (no TypeScript) so it can be imported from
// both the typed TypeScript surface (`src/build.ts`) and the dependency-free
// CLI binary (`bin/cli.mjs`) without needing a TypeScript loader.
//
// Do NOT inline this string in any other file. Edit it here and the two
// consumers automatically see the update.

/** @type {string} */
export const WORKER_WRAPPER_SOURCE = `// AUTO-GENERATED by @takazudo/zfb-adapter-cloudflare. Do not edit.
//
// Cloudflare Pages advanced mode entry. Forwards (request, env, ctx) to
// the inner zfb worker bundle, exposing env/ctx to user code via
// AsyncLocalStorage under a stable globalThis key.
//
// The same key is read by @takazudo/zfb-adapter-cloudflare's
// getCloudflareContext() inside the user bundle, so the two ends share
// state even though they live in separate ESM module instances.
//
// CF Pages advanced-mode contract: when _worker.js is present, every
// request hits the worker — static asset routing is OFF unless the
// worker explicitly delegates to env.ASSETS. We fall through on 404 so
// post-build artifacts that the inner router never sees (e.g.
// search-index.json, llms.txt, generated SSG HTML at trailing-slash
// canonical URLs) get served by the platform asset server.
import { AsyncLocalStorage } from "node:async_hooks";
import inner from "./_zfb_inner.mjs";

const STORAGE_KEY = "__zfb_cf_adapter_als__";

function getStorage() {
  const g = globalThis;
  let als = g[STORAGE_KEY];
  if (!als) {
    als = new AsyncLocalStorage();
    g[STORAGE_KEY] = als;
  }
  return als;
}

function canDelegateToAssets(env) {
  return Boolean(env && env.ASSETS && typeof env.ASSETS.fetch === "function");
}

export default {
  async fetch(request, env, ctx) {
    const store = { env, ctx, request };
    const response = await getStorage().run(store, () => inner.fetch(request));
    if (response.status === 404 && canDelegateToAssets(env)) {
      return env.ASSETS.fetch(request);
    }
    return response;
  },
};
`;
