// Single source of truth for the `_worker.js` wrapper string.
//
// Kept as a plain `.mjs` module (no TypeScript) so it can be imported from
// both the typed TypeScript surface (`src/build.ts`) and the dependency-free
// CLI binary (`bin/cli.mjs`) without needing a TypeScript loader.
//
// Do NOT inline this string in any other file. Edit it here and the two
// consumers automatically see the update.

/** @type {string} */
export const WORKER_WRAPPER_SOURCE = `// AUTO-GENERATED by @takazudo/zfb-adapter-cloudflare. Do not edit.
//
// Cloudflare Pages advanced mode entry. Forwards (request, env, ctx) to
// the inner zfb worker bundle, exposing env/ctx to user code via
// AsyncLocalStorage under a stable globalThis key.
//
// The same key is read by @takazudo/zfb-adapter-cloudflare's
// getCloudflareContext() inside the user bundle, so the two ends share
// state even though they live in separate ESM module instances.
//
// CF Pages advanced-mode contract: when _worker.js is present, every
// request hits the worker — static asset routing is OFF unless the
// worker explicitly delegates to env.ASSETS. The dispatch order below
// is deliberately "ASSETS first, inner on 404":
//
//   - GET/HEAD requests probe env.ASSETS first. CF Pages' asset server
//     handles the trailing-slash canonicalisation for SSG output (e.g.
//     "/docs/foo" → 308 → "/docs/foo/" → dist/docs/foo/index.html), so
//     prerendered routes get the build-time head-injected HTML
//     (<link rel="stylesheet">, <script type="module" src="/assets/
//     islands-…">). If we let the inner Hono router handle them first,
//     it would dynamic-SSR the page WITHOUT the prod head injection
//     (which is a build-time post-process, not a runtime concern), and
//     islands would never hydrate. See zfb#XXX (filed by Wave 10 of
//     the zudo-doc#1355 zfb-pipeline-gaps epic).
//   - On 404 from ASSETS, fall through to the inner zfb worker. This is
//     where genuinely dynamic routes (\`prerender = false\`, e.g.
//     \`pages/api/*.tsx\`) are served.
//   - Non-GET/HEAD requests skip ASSETS and go straight to the inner —
//     CF Pages assets are read-only by definition, and we want POSTs
//     (\`/api/ai-chat\`, etc.) to reach the SSR handler without a probe
//     that would always 405 / 404.
import { AsyncLocalStorage } from "node:async_hooks";
import inner from "./_zfb_inner.mjs";

const STORAGE_KEY = "__zfb_cf_adapter_als__";

function getStorage() {
  const g = globalThis;
  let als = g[STORAGE_KEY];
  if (!als) {
    als = new AsyncLocalStorage();
    g[STORAGE_KEY] = als;
  }
  return als;
}

function canDelegateToAssets(env) {
  return Boolean(env && env.ASSETS && typeof env.ASSETS.fetch === "function");
}

function isAssetProbeMethod(method) {
  // Only safe, side-effect-free methods probe the asset server. POST/
  // PUT/PATCH/DELETE go straight to the inner SSR worker.
  return method === "GET" || method === "HEAD";
}

export default {
  async fetch(request, env, ctx) {
    if (isAssetProbeMethod(request.method) && canDelegateToAssets(env)) {
      const assetResponse = await env.ASSETS.fetch(request);
      if (assetResponse.status !== 404) {
        return assetResponse;
      }
      // Fall through to the inner worker for genuinely dynamic routes.
    }
    const store = { env, ctx, request };
    return getStorage().run(store, () => inner.fetch(request));
  },
};
`;
