import {
  init as initRender,
  renderHtml,
  version as renderVersion,
  ZfbMdWasmTrapError as RenderTrapError,
  ZfbMdWasmTrapRecoveryLimitError as RenderTrapLimitError,
  __forceTrapForTests as forceRenderTrap,
  __getTrapRecoveryStateForTests as getRenderTrapState,
  type RenderHtmlResult,
  type Diagnostic,
  type DiagnosticSource,
  type ZfbMdWasmOptions,
  type PipelineOptions,
  type GfmOptions,
  type CodeHighlightMode,
  type CodeHighlightOptions,
  type MarkdownFeaturesConfig,
  type JsxRuntime,
  type HighlightRole,
} from "../dist/render.js";
import {
  init as initParse,
  parseToAst,
  toMdastRoot,
  MdastAdapterError,
  version as parseVersion,
  ZfbMdWasmTrapError as ParseTrapError,
  ZfbMdWasmTrapRecoveryLimitError as ParseTrapLimitError,
  __forceTrapForTests as forceParseTrap,
  __getTrapRecoveryStateForTests as getParseTrapState,
  type ParseToAstResult,
  type ParseToAstOptions,
  type ParseDialect,
  type FrontmatterPolicy,
  type ParsePipelineOptions,
  type Diagnostic as ParseDiagnostic,
  type DiagnosticSource as ParseDiagnosticSource,
  type AstPoint,
  type AstPosition,
  type RawMdastData,
  type MarkdownRsStop,
  type MdastNode,
  type MdastRoot,
  type UnknownMdastNode,
  type Root,
  type Paragraph,
  type Heading,
  type ThematicBreak,
  type Blockquote,
  type List,
  type ListItem,
  type Html,
  type Code,
  type Definition,
  type Text,
  type DirectiveNodeBase,
  type ContainerDirective,
  type LeafDirective,
  type TextDirective,
  type Emphasis,
  type Strong,
  type InlineCode,
  type Break,
  type Link,
  type Image,
  type ReferenceKind,
  type LinkReference,
  type ImageReference,
  type FootnoteDefinition,
  type FootnoteReference,
  type TableAlign,
  type Table,
  type TableRow,
  type TableCell,
  type Delete,
  type Yaml,
  type MdxFlowExpression,
  type MdxTextExpression,
  type MdxJsxFlowElement,
  type MdxJsxTextElement,
  type MdxJsxAttributeContent,
  type MdxJsxAttribute,
  type MdxJsxAttributeValueExpression,
  type MdxJsxExpressionAttribute,
} from "../dist/parse.js";

void [
  initRender,
  renderHtml,
  renderVersion,
  RenderTrapError,
  RenderTrapLimitError,
  forceRenderTrap,
  getRenderTrapState,
  initParse,
  parseToAst,
  toMdastRoot,
  MdastAdapterError,
  parseVersion,
  ParseTrapError,
  ParseTrapLimitError,
  forceParseTrap,
  getParseTrapState,
];

type RenderTypes = [
  RenderHtmlResult,
  Diagnostic,
  DiagnosticSource,
  ZfbMdWasmOptions,
  PipelineOptions,
  GfmOptions,
  CodeHighlightMode,
  CodeHighlightOptions,
  MarkdownFeaturesConfig,
  JsxRuntime,
  HighlightRole,
];
type ParseTypes = [
  ParseToAstResult,
  ParseToAstOptions,
  ParseDialect,
  FrontmatterPolicy,
  ParsePipelineOptions,
  ParseDiagnostic,
  ParseDiagnosticSource,
  AstPoint,
  AstPosition,
  RawMdastData,
  MarkdownRsStop,
  MdastNode,
  MdastRoot,
  UnknownMdastNode,
  Root,
  Paragraph,
  Heading,
  ThematicBreak,
  Blockquote,
  List,
  ListItem,
  Html,
  Code,
  Definition,
  Text,
  DirectiveNodeBase,
  ContainerDirective,
  LeafDirective,
  TextDirective,
  Emphasis,
  Strong,
  InlineCode,
  Break,
  Link,
  Image,
  ReferenceKind,
  LinkReference,
  ImageReference,
  FootnoteDefinition,
  FootnoteReference,
  TableAlign,
  Table,
  TableRow,
  TableCell,
  Delete,
  Yaml,
  MdxFlowExpression,
  MdxTextExpression,
  MdxJsxFlowElement,
  MdxJsxTextElement,
  MdxJsxAttributeContent,
  MdxJsxAttribute,
  MdxJsxAttributeValueExpression,
  MdxJsxExpressionAttribute,
];
declare const renderTypes: RenderTypes;
declare const parseTypes: ParseTypes;
void renderTypes;
void parseTypes;
