// Semantic parity and trust-boundary coverage for the split render/parse
// artifacts. These tests intentionally import the built package: the native
// oracle is the root entry, while the fixture JSON is generated by the same
// Rust API on the host target. `renderHtml` remains deliberately
// unsanitized; parity with that behavior is not a safety guarantee.
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import {
  parseToAst as rootParseToAst,
  renderHtml as rootRenderHtml,
  toMdastRoot as rootToMdastRoot,
  type ParseToAstOptions,
  type ZfbMdWasmOptions,
} from "../dist/index.js";
import { renderHtml as slimRenderHtml } from "../dist/render.js";
import {
  MdastAdapterError as SlimMdastAdapterError,
  parseToAst as slimParseToAst,
  toMdastRoot as slimToMdastRoot,
} from "../dist/parse.js";

const testDir = dirname(fileURLToPath(import.meta.url));
const fixturesRoot = join(testDir, "..", "..", "tests", "fixtures");

interface RenderFixture {
  slug: string;
  tier: "compile" | "renderHtml";
  input: string;
  options: Record<string, unknown>;
}

interface RenderManifest {
  fixtures: RenderFixture[];
}

interface ParseFixture {
  slug: string;
  source: string;
  options: ParseToAstOptions;
}

interface ParseManifest {
  fixtures: ParseFixture[];
}

interface DiagnosticFixture {
  slug: string;
  source: string;
  options: { filename: string };
}

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

const parityFixtures = readJson<RenderManifest>(
  join(fixturesRoot, "parity", "manifest.json"),
).fixtures;
const gfmFixtures = readJson<RenderManifest>(
  join(fixturesRoot, "gfm-parity", "manifest.json"),
).fixtures;
const parseFixtures = readJson<ParseManifest>(
  join(fixturesRoot, "parse-to-ast", "manifest.json"),
).fixtures;
const diagnosticFixtures = readJson<{ fixtures: DiagnosticFixture[] }>(
  join(fixturesRoot, "parse-to-ast", "diagnostics.json"),
).fixtures;

describe("./render semantic parity", () => {
  for (const corpus of [
    ["parity", parityFixtures, "parity"],
    ["gfm", gfmFixtures, "gfm-parity"],
  ] as const) {
    const [name, fixtures, directory] = corpus;
    for (const fixture of fixtures.filter(({ tier }) => tier === "renderHtml")) {
      it(`${name}/${fixture.slug} matches root and the native oracle`, async () => {
        const source = readFileSync(join(fixturesRoot, directory, fixture.input), "utf8");
        const expected = readJson<unknown>(
          join(fixturesRoot, directory, "expected", `${fixture.slug}.json`),
        );
        const options = fixture.options as ZfbMdWasmOptions;
        const [root, slim] = await Promise.all([
          rootRenderHtml(source, options),
          slimRenderHtml(source, options),
        ]);

        // The root result is the full/native oracle's byte/value contract;
        // the split artifact must preserve it exactly for every applicable
        // Markdown fixture, including frontmatter and pipeline options.
        expect(root).toStrictEqual(expected);
        expect(slim).toStrictEqual(root);
        expect(JSON.stringify(slim)).toBe(JSON.stringify(expected));
      });
    }
  }

  it("keeps raw HTML unsanitized with identical root/slim output", async () => {
    // Trust intent: this is an intentionally unsanitized HTML renderer. The
    // package does not claim to make author HTML safe; callers must sanitize
    // before displaying untrusted content when that is their requirement.
    const source =
      '<script type="application/x-zfb-security">globalThis.__zfbSlimSecurityProbe = 1</script>\n';
    const options = { filename: "raw-html.md" } satisfies ZfbMdWasmOptions;
    const [root, slim] = await Promise.all([
      rootRenderHtml(source, options),
      slimRenderHtml(source, options),
    ]);
    expect(slim).toStrictEqual(root);
    expect(slim.diagnostics).toEqual([]);
    expect(slim.html).toContain("<script");
    expect(slim.html).toContain("globalThis.__zfbSlimSecurityProbe = 1");
  });

  it("preserves structured UTF-16 diagnostics from root/native behavior", async () => {
    for (const fixture of diagnosticFixtures) {
      const [root, slim] = await Promise.all([
        rootRenderHtml(fixture.source, fixture.options),
        slimRenderHtml(fixture.source, fixture.options),
      ]);
      expect(slim, fixture.slug).toStrictEqual(root);
      expect(slim.diagnostics).toHaveLength(1);
      expect(slim.diagnostics[0]).toMatchObject({
        source: "markdown",
        line: expect.any(Number),
        column: expect.any(Number),
      });
    }
  });

  it("preserves MDX render behavior without exposing compile", async () => {
    const source = '# MDX\n\n<Widget data-id="raw" />\n\n{1 + 2}\n';
    const options = { filename: "component.mdx" } satisfies ZfbMdWasmOptions;
    const [root, slim] = await Promise.all([
      rootRenderHtml(source, options),
      slimRenderHtml(source, options),
    ]);
    expect(slim).toStrictEqual(root);
    expect(slim.diagnostics).toEqual([]);
  });

  it("keeps CommonMark inference and explicit MDX overrides identical", async () => {
    const source = "Budget <8 ms\n";
    for (const options of [
      { filename: "preview.md" },
      { filename: "preview.mdx", dialect: "markdown" as const },
      { filename: "preview.md", dialect: "mdx" as const },
    ]) {
      const [root, slim] = await Promise.all([
        rootRenderHtml(source, options),
        slimRenderHtml(source, options),
      ]);
      expect(slim, JSON.stringify(options)).toStrictEqual(root);
    }
  });
});

describe("./parse semantic parity", () => {
  for (const fixture of parseFixtures) {
    it(`${fixture.slug} matches the root parser`, async () => {
      const [root, slim] = await Promise.all([
        rootParseToAst(fixture.source, fixture.options),
        slimParseToAst(fixture.source, fixture.options),
      ]);
      // This corpus spans Markdown/MDX inference and overrides, every
      // frontmatter policy, directives/GFM, custom nodes, and UTF-16 points.
      expect(slim).toStrictEqual(root);
    });
  }

  it("keeps MDX JSX, expressions, and ESM-shaped source inert", async () => {
    // Trust intent: parsing must return author syntax as data. No slim path
    // may import, compile, evaluate, or execute the expression/module text.
    const probe = "__zfbSlimSecurityProbe";
    const globalProbe = globalThis as Record<string, unknown>;
    delete globalProbe[probe];
    const source = [
      "<Widget value={globalThis.__zfbSlimSecurityProbe = 1} />",
      "",
      "{globalThis.__zfbSlimSecurityProbe = 2}",
      "",
      "export const dangerous = globalThis.__zfbSlimSecurityProbe = 3",
      "",
    ].join("\n");
    const out = await slimParseToAst(source, { filename: "inert.mdx" });
    expect(out.diagnostics).toEqual([]);
    expect(out.ast).not.toBeNull();
    expect(globalProbe[probe]).toBeUndefined();
    const serialized = JSON.stringify(out.ast);
    expect(serialized).toContain("mdxJsxFlowElement");
    expect(serialized).toContain("mdxFlowExpression");
    expect(serialized).toContain("globalThis.__zfbSlimSecurityProbe");
    // markdown-rs intentionally degrades top-level ESM to source text in
    // this API, but it still remains inert data rather than executable code.
    expect(serialized).toContain("export const dangerous");
  });

  it("adapts successful roots and rejects malformed/unknown nodes", async () => {
    const out = await slimParseToAst("# Heading\n\nParagraph\n", { filename: "post.md" });
    if (!out.ast) throw new Error("fixture must parse");
    expect(() => slimToMdastRoot(out.ast)).not.toThrow();
    expect(() => rootToMdastRoot(out.ast)).not.toThrow();

    const unknown = structuredClone(out.ast);
    Object.defineProperty(unknown.children[0], "type", { value: "futureWidget" });
    expect(() => slimToMdastRoot(unknown)).toThrowError(
      expect.objectContaining({ path: "$.children[0]", nodeType: "futureWidget" }),
    );
    expect(() => slimToMdastRoot(null)).toThrowError(
      expect.objectContaining({ path: "$", nodeType: null }),
    );
    try {
      slimToMdastRoot(unknown);
    } catch (error) {
      expect(error).toBeInstanceOf(SlimMdastAdapterError);
    }
  });
});
