#!/usr/bin/env bash
# update-homebrew-formula.sh
#
# Fetches sha256 checksums from the zudo-front-builder GitHub Release and
# writes (or updates) Formula/zfb.rb in the Homebrew tap directory.
#
# Usage:
#   ./scripts/update-homebrew-formula.sh <version> [--tap-path PATH] [--push]
#
# <version>   Tag name or bare semver, e.g. "v0.2.0" or "0.2.0". The script
#             accepts both and normalises internally.
#
# --tap-path  Path to the Homebrew tap repo checkout.
#             Default: ${HOME}/repos/myoss/homebrew-tap
#
# --push      After writing Formula/zfb.rb, git add + commit + push.
#             Without this flag the file is written AND printed to stdout.
#
# Environment overrides (useful for offline / CI testing):
#   ZFB_SHA256_SOURCE_DIR  When set, the script reads *.sha256 files from
#                          this local directory instead of fetching from GitHub.
#                          File names must match the archive basename, e.g.:
#                            zfb-0.2.0-aarch64-apple-darwin.tar.gz.sha256
set -euo pipefail

# ── Argument parsing ──────────────────────────────────────────────────────────

version_arg=""
tap_path="${HOME}/repos/Takazudo/homebrew-tap"
do_push=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tap-path)
      tap_path="$2"
      shift 2
      ;;
    --push)
      do_push=true
      shift
      ;;
    -*)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
    *)
      if [[ -z "$version_arg" ]]; then
        version_arg="$1"
      else
        echo "Unexpected positional argument: $1" >&2
        exit 1
      fi
      shift
      ;;
  esac
done

if [[ -z "$version_arg" ]]; then
  echo "Usage: $0 <version> [--tap-path PATH] [--push]" >&2
  exit 1
fi

# ── Normalise version ─────────────────────────────────────────────────────────

# Strip leading "v" to get a bare semver (used in archive names and formula version).
semver="${version_arg#v}"
# Ensure the tag always has a "v" prefix (used in the GitHub release URL).
version_tag="v${semver}"

echo "==> Updating formula for zfb ${version_tag} (semver: ${semver})"
echo "    tap-path: ${tap_path}"

# ── Asset URL base ────────────────────────────────────────────────────────────

# GH Release download URL pattern — contract locked by S3 (#381).
gh_base="https://github.com/Takazudo/zudo-front-builder/releases/download/${version_tag}"

# ── Fetch sha256 checksums ────────────────────────────────────────────────────

# Target triples that appear in macOS archives (primary for Homebrew).
darwin_arm64_triple="aarch64-apple-darwin"
darwin_x64_triple="x86_64-apple-darwin"

# Linux triples — included via on_linux do block.
linux_arm64_triple="aarch64-unknown-linux-gnu"
linux_x64_triple="x86_64-unknown-linux-gnu"

# Returns the sha256 hex string for a given target triple.
# If ZFB_SHA256_SOURCE_DIR is set, reads from a local file.
# Otherwise fetches from GitHub Releases.
fetch_sha256() {
  local triple="$1"
  local archive="zfb-${semver}-${triple}.tar.gz"
  local sha256_file="${archive}.sha256"

  local content
  if [[ -n "${ZFB_SHA256_SOURCE_DIR:-}" ]]; then
    local local_path="${ZFB_SHA256_SOURCE_DIR}/${sha256_file}"
    if [[ ! -f "$local_path" ]]; then
      echo "ERROR: ZFB_SHA256_SOURCE_DIR set but file not found: $local_path" >&2
      exit 1
    fi
    content="$(cat "$local_path")"
  else
    local url="${gh_base}/${sha256_file}"
    echo "    Fetching ${url} ..." >&2
    content="$(curl -fsSL "$url")"
  fi

  # GNU sha256sum format: "<64-hex>  <archive-basename>"
  # Parse the first whitespace-delimited field.
  local hash
  hash="$(echo "$content" | awk '{print $1}')"

  if [[ ! "$hash" =~ ^[0-9a-f]{64}$ ]]; then
    echo "ERROR: Unexpected checksum format for ${triple}: '${hash}'" >&2
    exit 1
  fi

  echo "$hash"
}

echo "==> Fetching checksums ..."
sha256_darwin_arm64="$(fetch_sha256 "$darwin_arm64_triple")"
sha256_darwin_x64="$(fetch_sha256 "$darwin_x64_triple")"
sha256_linux_arm64="$(fetch_sha256 "$linux_arm64_triple")"
sha256_linux_x64="$(fetch_sha256 "$linux_x64_triple")"

echo "    darwin-arm64 : ${sha256_darwin_arm64}"
echo "    darwin-x64   : ${sha256_darwin_x64}"
echo "    linux-arm64  : ${sha256_linux_arm64}"
echo "    linux-x64    : ${sha256_linux_x64}"

# ── Generate formula ──────────────────────────────────────────────────────────

formula="$(cat <<FORMULA
# Auto-generated by scripts/update-homebrew-formula.sh — do not edit manually.
# Regenerate with: ./scripts/update-homebrew-formula.sh ${version_tag} --push
class Zfb < Formula
  desc "Rust-built static-site engine — millisecond rebuilds, single binary"
  homepage "https://takazudomodular.com/pj/zudo-front-builder/"
  # Source: GitHub Releases from Takazudo/zudo-front-builder (not the npm registry).
  # Archive contract: zfb-{semver}-{target-triple}.tar.gz, one file at archive root.
  license "MIT"
  version "${semver}"

  on_macos do
    on_arm do
      url "${gh_base}/zfb-${semver}-${darwin_arm64_triple}.tar.gz"
      sha256 "${sha256_darwin_arm64}"
    end

    on_intel do
      url "${gh_base}/zfb-${semver}-${darwin_x64_triple}.tar.gz"
      sha256 "${sha256_darwin_x64}"
    end
  end

  on_linux do
    on_arm do
      url "${gh_base}/zfb-${semver}-${linux_arm64_triple}.tar.gz"
      sha256 "${sha256_linux_arm64}"
    end

    on_intel do
      url "${gh_base}/zfb-${semver}-${linux_x64_triple}.tar.gz"
      sha256 "${sha256_linux_x64}"
    end
  end

  def install
    bin.install "zfb"
  end

  test do
    system bin/"zfb", "--version"
  end
end
FORMULA
)"

# ── Write formula file ────────────────────────────────────────────────────────

formula_dir="${tap_path}/Formula"
formula_file="${formula_dir}/zfb.rb"

mkdir -p "$formula_dir"
echo "$formula" > "$formula_file"

echo "==> Written: ${formula_file}"

if [[ "$do_push" == "false" ]]; then
  echo "--- Formula contents ---"
  echo "$formula"
  echo "--- (use --push to commit and push to the tap) ---"
  exit 0
fi

# ── Git add / commit / push ───────────────────────────────────────────────────

echo "==> Committing and pushing to tap ..."
git -C "$tap_path" add Formula/zfb.rb
if ! git -C "$tap_path" diff --cached --quiet; then
  git -C "$tap_path" commit -m "zfb ${semver}"
else
  echo "    formula unchanged — skipping commit"
fi
git -C "$tap_path" push

echo "==> Done — Formula/zfb.rb committed and pushed for zfb ${version_tag}"
