//! Level 1/T0 YAML parser compatibility contract.
//!
//! The corpus and snapshot in `fixtures/yaml/` are a durable characterization
//! of the three `serde_yaml` behaviors used by zfb-content: deserializing into
//! `serde_json::Value`, error `Display`, and error locations. The snapshot is
//! intentionally checked in rather than generated by this test. A future
//! parser candidate only needs to replace the `YamlAdapter` implementation;
//! the corpus, baseline, and assertions remain unchanged so differences are
//! reported mechanically. The bounded alias-expansion case captures the
//! current repetition-limit behavior without attempting an unsafe allocation.

use std::collections::BTreeSet;
use std::path::Path;

use serde::Deserialize;
use serde_json::Value;

const CORPUS: &str = include_str!("fixtures/yaml/serde_yaml_corpus.json");
const BASELINE: &str = include_str!("fixtures/yaml/serde_yaml_baseline.json");
const CURRENT_ADAPTER_NAME: &str = "serde_yaml 0.9.34+deprecated";

const REQUIRED_CATEGORIES: &[&str] = &[
    "anchors-aliases",
    "merge-keys",
    "non-string-keys",
    "scalar-edge-cases",
    "unicode-bom-crlf-emoji",
    "malformed-input",
    "explicit-tags",
    "duplicate-keys",
    "non-finite-overflowing-numbers",
    "alias-anchor-resource-limits",
];

#[derive(Debug, Deserialize)]
struct Corpus {
    schema_version: u32,
    cases: Vec<CorpusCase>,
}

#[derive(Debug, Deserialize)]
struct CorpusCase {
    name: String,
    category: String,
    yaml: String,
    document: Option<String>,
    document_expect: Option<DocumentExpectation>,
    document_location: Option<DocumentLocation>,
}

#[derive(Debug, Deserialize)]
struct DocumentExpectation {
    value: Value,
    body: String,
    body_offset: usize,
}

#[derive(Debug, Deserialize)]
struct DocumentLocation {
    line: usize,
    column: usize,
}

#[derive(Debug, Deserialize)]
struct Baseline {
    schema_version: u32,
    adapter: String,
    cases: Vec<BaselineCase>,
}

#[derive(Debug, Deserialize, PartialEq)]
struct BaselineCase {
    name: String,
    category: String,
    observation: Observation,
}

#[derive(Debug, Deserialize, PartialEq)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum Observation {
    Success {
        value: Value,
    },
    Error {
        display: String,
        location: Option<Location>,
    },
}

#[derive(Debug, Deserialize, PartialEq)]
struct Location {
    line: usize,
    column: usize,
    index: usize,
}

/// Adapter boundary for a candidate parser.
///
/// The adapter returns only the surface zfb consumes. In particular, it does
/// not expose `serde_yaml::Value`; a candidate can normalize its own error
/// type to this test observation without changing the immutable baseline.
trait YamlAdapter {
    fn parse(&self, yaml: &str) -> Observation;
}

/// Current production behavior. Keep the baseline fixture tied to this
/// adapter until a candidate topic intentionally evaluates a replacement.
struct SerdeYamlAdapter;

impl YamlAdapter for SerdeYamlAdapter {
    fn parse(&self, yaml: &str) -> Observation {
        match serde_yaml::from_str::<Value>(yaml) {
            Ok(value) => Observation::Success { value },
            Err(error) => Observation::Error {
                display: error.to_string(),
                location: error.location().map(|location| Location {
                    line: location.line(),
                    column: location.column(),
                    index: location.index(),
                }),
            },
        }
    }
}

fn corpus() -> Corpus {
    serde_json::from_str(CORPUS).expect("YAML compatibility corpus must be valid JSON")
}

fn baseline() -> Baseline {
    serde_json::from_str(BASELINE).expect("YAML compatibility baseline must be valid JSON")
}

fn observe<A: YamlAdapter>(adapter: &A, corpus: &Corpus) -> Vec<BaselineCase> {
    corpus
        .cases
        .iter()
        .map(|case| BaselineCase {
            name: case.name.clone(),
            category: case.category.clone(),
            observation: adapter.parse(&case.yaml),
        })
        .collect()
}

#[test]
fn current_serde_yaml_matches_immutable_baseline() {
    let corpus = corpus();
    let baseline = baseline();

    assert_eq!(corpus.schema_version, baseline.schema_version);
    assert_eq!(baseline.adapter, CURRENT_ADAPTER_NAME);
    assert_eq!(observe(&SerdeYamlAdapter, &corpus), baseline.cases);
}

#[test]
fn corpus_covers_every_named_compatibility_category() {
    let corpus = corpus();
    let mut names = BTreeSet::new();
    let categories: BTreeSet<_> = corpus
        .cases
        .iter()
        .map(|case| case.category.as_str())
        .collect();

    for case in &corpus.cases {
        assert!(
            names.insert(&case.name),
            "duplicate corpus case: {}",
            case.name
        );
        assert!(!case.yaml.is_empty(), "empty YAML input: {}", case.name);
    }
    for category in REQUIRED_CATEGORIES {
        assert!(
            categories.contains(category),
            "missing required YAML compatibility category: {category}"
        );
    }
}

#[test]
fn bom_crlf_emoji_frontmatter_document_contract_is_pinned() {
    let corpus = corpus();
    let case = corpus
        .cases
        .iter()
        .find(|case| case.name == "unicode-crlf-and-emoji")
        .expect("Unicode document case must remain in the corpus");
    let document = case.document.as_deref().expect("document fixture");
    let expected = case.document_expect.as_ref().expect("document expectation");

    let extracted = zfb_content::frontmatter::extract(Path::new("unicode.md"), document)
        .expect("BOM + CRLF frontmatter must extract");
    assert_eq!(extracted.value, expected.value);
    assert_eq!(extracted.body.as_deref(), Some(expected.body.as_str()));
    assert_eq!(extracted.body_offset, Some(expected.body_offset));
}

#[test]
fn hard_location_pins_survive_frontmatter_coordinate_mapping() {
    let corpus = corpus();
    let adapter = SerdeYamlAdapter;

    for name in [
        "malformed-unicode-location",
        "malformed-flow-sequence-at-eof",
    ] {
        let case = corpus
            .cases
            .iter()
            .find(|case| case.name == name)
            .unwrap_or_else(|| panic!("missing hard location case: {name}"));
        let document = case.document.as_deref().expect("location document fixture");
        let expected_source = case
            .document_location
            .as_ref()
            .expect("source location expectation");

        let observation = adapter.parse(&case.yaml);
        let Observation::Error {
            location: Some(location),
            ..
        } = observation
        else {
            panic!("{name} must remain a located parser error");
        };

        let expected_yaml = match name {
            "malformed-unicode-location" => (1, 8, 16),
            "malformed-flow-sequence-at-eof" => (2, 1, 12),
            _ => unreachable!("all hard location cases are listed above"),
        };
        assert_eq!(
            (location.line, location.column, location.index),
            expected_yaml,
            "{name}: raw serde_yaml location"
        );

        let yaml_start = yaml_start_in_document(document);
        let source_offset = yaml_start + location.index;
        let indexed_point = utf16_point(document, source_offset);
        // An unclosed flow collection reports a virtual next YAML line while
        // keeping its byte index at the preceding line's end. zfb preserves
        // that serde_yaml line/column pair when the index-derived line does
        // not agree.
        let (line, column) = if indexed_point.0 == location.line + 1 {
            indexed_point
        } else {
            (location.line + 1, location.column)
        };

        // The parser reports line relative to the YAML slice. zfb's
        // frontmatter diagnostic shifts it past the opener, while its index
        // is used to recover UTF-16 columns. These are the two existing wasm
        // compatibility pins that a replacement must preserve.
        assert_eq!(location.line + 1, expected_source.line, "{name}: line");
        assert_eq!(
            (line, column),
            (expected_source.line, expected_source.column),
            "{name}: source UTF-16 point"
        );
    }
}

fn yaml_start_in_document(document: &str) -> usize {
    let bom_len = usize::from(document.starts_with('\u{feff}')) * '\u{feff}'.len_utf8();
    let logical = &document[bom_len..];
    let yaml = logical
        .strip_prefix("---\n")
        .or_else(|| logical.strip_prefix("---\r\n"))
        .expect("location document must begin with a frontmatter opener");
    document.len() - yaml.len()
}

fn utf16_point(source: &str, offset: usize) -> (usize, usize) {
    assert!(source.is_char_boundary(offset), "location splits UTF-8");
    let prefix = &source[..offset];
    let line = prefix.bytes().filter(|byte| *byte == b'\n').count() + 1;
    let line_start = prefix.rfind('\n').map_or(0, |index| index + 1);
    let column = source[line_start..offset].encode_utf16().count() + 1;
    (line, column)
}
