//! Syntect-based syntax highlighting.
//!
//! Provides a [`Highlighter`] cache around syntect's [`SyntaxSet`] and
//! [`ThemeSet`], plus an [`Highlighter::highlight`] entry point that returns
//! an HTML fragment of the form
//! `<pre class="syntect-{theme-slug}"><code>…spans…</code></pre>`.
//!
//! The class on the `<pre>` element lets users theme blocks via CSS while still
//! getting syntect-coloured spans inside.
//!
//! ## Bundled-set caching
//!
//! Deserializing syntect's bundled `SyntaxSet` and `ThemeSet` is expensive
//! (several milliseconds each). Both are loaded **once per process** via
//! [`BUNDLED_SYNTAX_SET`] and [`BUNDLED_THEME_SET`] (`std::sync::LazyLock`),
//! then shared — `Highlighter` borrows the syntax set via `Arc` and clones
//! only the theme map when user-supplied `.tmTheme` files must be layered on
//! top of the defaults.

// Backend contract (zfb#1573): without one of these features, syntect itself
// fails first with E0433 `regex_impl` errors (its parsing::regex has no
// implementation), so plain builds never reach this guard — it exists for
// tooling that type-checks this crate against a pre-built graph, and to make
// the feature contract greppable at the point of use.
#[cfg(not(any(feature = "syntect-onig", feature = "syntect-fancy")))]
compile_error!(
    "zfb-content needs a syntect regex backend: enable feature `syntect-onig` (native default) or `syntect-fancy` (wasm-safe); `default-features = false` alone leaves syntect without a regex implementation"
);

use std::collections::BTreeMap;
use std::path::Path;
use std::sync::{Arc, LazyLock};

use syntect::easy::{HighlightLines, ScopeRegionIterator};
use syntect::highlighting::{Color, Theme, ThemeSet};
use syntect::html::{styled_line_to_highlighted_html, IncludeBackground};
use syntect::parsing::{ParseState, ScopeStack, SyntaxSet};
use syntect::util::LinesWithEndings;
use zfb_types::escape_html;

use crate::hi_roles::classify;

/// Default prefix for semantic class-mode code highlighting.
///
/// Kept beside the renderer so native config and direct consumers (including
/// the WASM facade) cannot grow independent defaults.
pub const DEFAULT_CLASS_HIGHLIGHT_PREFIX: &str = "hi-";

/// The custom `SyntaxSet` dump (issue #1848): syntect's own bundled defaults
/// plus the TOML, TypeScript, and TSX grammars committed under
/// `assets/syntaxes/`, regenerated by `tests/bin/generate_syntax_dump.rs`.
/// `SyntaxSet` is immutable after `SyntaxSetBuilder::build()`, so there is no
/// way to merge extra grammars into `load_defaults_newlines()`'s result at
/// runtime — this dump is a full replacement built ahead of time instead.
static BUNDLED_SYNTAX_SET_DUMP: &[u8] = include_bytes!("../assets/syntax-set.packdump");

/// Bundled `SyntaxSet` loaded once per process.
///
/// `SyntaxSet::from_uncompressed_data` deserializes the dump embedded above.
/// The call is safe to make from any thread; `LazyLock` ensures it happens
/// exactly once. Dumps store regex patterns as strings with lazy
/// per-backend compilation, so this one dump correctly serves both the
/// native `onig` backend and the wasm `fancy` backend.
static BUNDLED_SYNTAX_SET: LazyLock<Arc<SyntaxSet>> = LazyLock::new(|| {
    Arc::new(
        syntect::dumps::from_uncompressed_data(BUNDLED_SYNTAX_SET_DUMP)
            .expect("assets/syntax-set.packdump must deserialize; regenerate with `cargo run -p zfb-content --bin generate_syntax_dump --features generate-syntax-dump`"),
    )
});

/// Test-only accessor for the process-wide bundled syntax set — lets other
/// modules' tests (e.g. `hi_roles`) exercise the SAME custom dump
/// `Highlighter` uses instead of duplicating `SyntaxSet::load_defaults_newlines()`
/// (which lacks the extra grammars above).
#[cfg(test)]
pub(crate) fn bundled_syntax_set_for_tests() -> Arc<SyntaxSet> {
    Arc::clone(&BUNDLED_SYNTAX_SET)
}

/// Bundled `ThemeSet` loaded once per process.
///
/// `ThemeSet::load_defaults()` deserializes the bundled themes. Loaded once
/// and shared via `Arc`; per-Pipeline user themes are layered on a clone of
/// `theme_set` so the base is never mutated.
static BUNDLED_THEME_SET: LazyLock<Arc<ThemeSet>> =
    LazyLock::new(|| Arc::new(ThemeSet::load_defaults()));

/// A single `.tmTheme` parse failure, carrying the file path.
#[derive(Debug)]
pub struct ThemeFileError {
    pub path: std::path::PathBuf,
    pub message: String,
}

impl std::fmt::Display for ThemeFileError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.path.display(), self.message)
    }
}

/// Cached syntect resources.
///
/// The `syntax_set` is shared across all `Highlighter` instances via `Arc`
/// (pointing at [`BUNDLED_SYNTAX_SET`]). The `theme_set` starts as a clone of
/// [`BUNDLED_THEME_SET`] so that per-Pipeline user themes can be inserted
/// without affecting the shared base.
pub struct Highlighter {
    /// Shared reference to the process-wide bundled syntax set.
    syntax_set: Arc<SyntaxSet>,
    /// Per-instance theme map — starts as a clone of [`BUNDLED_THEME_SET`] so
    /// user-supplied `.tmTheme` files can be layered on without mutating the
    /// shared base.
    theme_set: ThemeSet,
    default_theme: String,
}

impl Highlighter {
    /// Construct with bundled defaults (syntect's `load_defaults_newlines` syntaxes
    /// and the built-in theme set).
    ///
    /// Bundled defaults give us at minimum:
    /// `base16-ocean.dark`, `base16-ocean.light`, `InspiredGitHub`,
    /// `Solarized (dark)`, `Solarized (light)`.
    ///
    /// The bundled `SyntaxSet` is shared via [`BUNDLED_SYNTAX_SET`] (loaded once
    /// per process). The `ThemeSet` is cloned from [`BUNDLED_THEME_SET`] so
    /// per-instance user themes can be added without affecting the shared base.
    pub fn new() -> Self {
        // Clone the theme map from the shared base so user-supplied themes can
        // be inserted without affecting other Highlighter instances.
        // `ThemeSet` itself doesn't implement `Clone`, but `Theme` does, so we
        // manually copy the map.
        let theme_set = ThemeSet {
            themes: BUNDLED_THEME_SET
                .themes
                .iter()
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect(),
        };
        Self {
            syntax_set: Arc::clone(&BUNDLED_SYNTAX_SET),
            theme_set,
            default_theme: "base16-ocean.dark".to_string(),
        }
    }

    /// List built-in theme names.
    pub fn theme_names(&self) -> Vec<String> {
        let mut names: Vec<String> = self.theme_set.themes.keys().cloned().collect();
        names.sort();
        names
    }

    /// Set the default theme used when callers don't pass one.
    /// Returns `Err` if the theme isn't loaded.
    pub fn set_default_theme(&mut self, name: &str) -> Result<(), HighlightError> {
        if !self.theme_set.themes.contains_key(name) {
            return Err(HighlightError::UnknownTheme(name.to_string()));
        }
        self.default_theme = name.to_string();
        Ok(())
    }

    /// Load extra `.tmTheme` files from `dir`.
    ///
    /// Each `.tmTheme` file is parsed individually.  On the first parse
    /// failure the function returns [`HighlightError::ThemeFileParse`] with
    /// the failing file's path attached — this is the acceptance-criterion
    /// "surface file path + parse error" guarantee.  IO errors reading the
    /// directory itself are returned as [`HighlightError::ThemeLoad`].
    ///
    /// The directory **must exist** before calling this function.  A missing
    /// directory is reported as an [`HighlightError::ThemeLoad`] IO error.
    pub fn load_themes_from_dir(&mut self, dir: &Path) -> Result<(), HighlightError> {
        let entries = std::fs::read_dir(dir)?;
        for entry in entries {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("tmTheme") {
                continue;
            }
            // Parse the individual file so we can attach its path to any error.
            let theme = ThemeSet::get_theme(&path).map_err(|e| {
                HighlightError::ThemeFileParse(ThemeFileError {
                    path: path.clone(),
                    message: e.to_string(),
                })
            })?;
            // Derive the theme name from its plist `name` key (already stored
            // in `theme.name`) or fall back to the file stem so the theme
            // is always addressable.
            let name = theme
                .name
                .as_deref()
                .filter(|n| !n.is_empty())
                .map(|n| n.to_string())
                .unwrap_or_else(|| {
                    path.file_stem()
                        .and_then(|s| s.to_str())
                        .unwrap_or("unknown")
                        .to_string()
                });
            self.theme_set.themes.insert(name, theme);
        }
        Ok(())
    }

    /// Resolve a fence language tag to a bundled syntax, applying the
    /// [`resolve_alias`] table. Shared by every highlight path
    /// ([`Self::highlight_lines`], [`Self::highlight_lines_dual`],
    /// [`Self::highlight_lines_classes`]) so alias handling lives in one place.
    /// `None`/empty `lang` or an unresolvable tag yields `None`, and each
    /// caller degrades to its own escaped fallback.
    fn resolve_syntax(&self, lang: Option<&str>) -> Option<&syntect::parsing::SyntaxReference> {
        lang.filter(|s| !s.is_empty()).and_then(|l| {
            self.syntax_set.find_syntax_by_token(l).or_else(|| {
                resolve_alias(l)
                    .iter()
                    .find_map(|name| self.syntax_set.find_syntax_by_name(name))
            })
        })
    }

    /// Highlight a code block.
    ///
    /// * `code` - raw source code (no surrounding HTML).
    /// * `lang` - language identifier from the markdown fence (`"rust"`, `"ts"`,
    ///   `"javascript"`, …). `None` or empty falls back to plain text.
    /// * `theme` - optional theme override; falls back to the configured default.
    ///
    /// Returns an HTML fragment of the form
    /// `<pre class="syntect-{theme-slug}"><code>…spans…</code></pre>`.
    /// `{theme-slug}` is the theme name lowercased with non-alphanumerics
    /// collapsed to `'-'`.
    ///
    /// If `lang` is unknown, returns the safe fallback
    /// `<pre><code>{html-escaped code}</code></pre>`.
    pub fn highlight(
        &self,
        code: &str,
        lang: Option<&str>,
        theme: Option<&str>,
    ) -> Result<String, HighlightError> {
        let result = self.highlight_lines(code, lang, theme)?;
        let spans: String = result.lines.concat();
        Ok(format!(
            "<pre class=\"syntect-{}\"><code>{spans}</code></pre>",
            result.theme_slug
        ))
    }

    /// Highlight a code block, returning per-line HTML fragments and the theme
    /// slug rather than a single HTML string.
    ///
    /// * `code` - raw source code (no surrounding HTML).
    /// * `lang` - language identifier from the markdown fence.
    /// * `theme` - optional theme override; falls back to the configured default.
    ///
    /// Returns a [`HighlightedLines`] value carrying:
    /// - `theme_slug`: the CSS-safe theme name (used as the `syntect-{slug}`
    ///   class on `<pre>`).
    /// - `lines`: one HTML fragment per source line (from
    ///   `styled_line_to_highlighted_html`). On the fallback path (unknown lang
    ///   or tokenization error) each line is the HTML-escaped source text with
    ///   a trailing newline preserved; the `fallback` flag is `true` in that case.
    pub fn highlight_lines(
        &self,
        code: &str,
        lang: Option<&str>,
        theme: Option<&str>,
    ) -> Result<HighlightedLines, HighlightError> {
        // Normalize empty theme to the configured default for symmetry with `lang`.
        let theme_name = theme
            .filter(|s| !s.is_empty())
            .unwrap_or(&self.default_theme);
        let theme_obj: &Theme = self
            .theme_set
            .themes
            .get(theme_name)
            .ok_or_else(|| HighlightError::UnknownTheme(theme_name.to_string()))?;

        let slug = theme_slug(theme_name);

        let syntax = self.resolve_syntax(lang);

        let Some(syntax) = syntax else {
            return Ok(fallback_lines(code, &slug));
        };

        let mut h = HighlightLines::new(syntax, theme_obj);
        let mut lines: Vec<String> = Vec::new();
        for line in LinesWithEndings::from(code) {
            let regions = match h.highlight_line(line, &self.syntax_set) {
                Ok(r) => r,
                // Path B: tokenization error — degrade to themed fallback instead of
                // bubbling Err so callers never see a bare unthemed <pre><code>.
                Err(_) => return Ok(fallback_lines(code, &slug)),
            };
            match styled_line_to_highlighted_html(&regions[..], IncludeBackground::No) {
                Ok(line_html) => lines.push(line_html),
                Err(_) => return Ok(fallback_lines(code, &slug)),
            }
        }

        Ok(HighlightedLines {
            theme_slug: slug,
            lines,
            fallback: false,
        })
    }

    /// Highlight a code block **twice** (a light theme and a dark theme) and
    /// emit per-token CSS *custom properties* (`--shiki-light` / `--shiki-dark`)
    /// instead of an inline `color:`.
    ///
    /// This is the engine primitive for dual-theme (light + dark) rendering: a
    /// single HTML payload carries both colours per token, and CSS picks which
    /// custom property to apply based on the active colour scheme. The variable
    /// names mirror Shiki's dual-theme convention so downstream CSS is familiar.
    ///
    /// * `code` - raw source code (no surrounding HTML).
    /// * `lang` - language identifier from the markdown fence.
    /// * `theme_light` / `theme_dark` - theme names; BOTH must resolve or the
    ///   call returns [`HighlightError::UnknownTheme`] (same path as the
    ///   single-theme method).
    ///
    /// Returns a [`DualHighlightedLines`] carrying:
    /// - `lines`: one HTML fragment per source line. On the highlighted path each
    ///   token is `<span style="--shiki-light:#…;--shiki-dark:#…">{escaped}</span>`.
    ///   On the fallback path each entry is the HTML-escaped source line with no
    ///   colour vars.
    /// - `light_bg` / `dark_bg`: each theme's background as `#rrggbb`, or `None`
    ///   when that theme defines no `settings.background` (colour-only `.tmTheme`).
    /// - `fallback`: `true` when the themed-fallback path was used (unknown lang,
    ///   tokenization error, or a per-line region-alignment mismatch).
    ///
    /// ## Region-alignment guard
    ///
    /// Tokenization is syntax/scope-driven, not theme-driven, so highlighting the
    /// same syntax under two themes yields region lists whose text slices
    /// concatenate to identical per-line text. This is *asserted* per line: on any
    /// mismatch the method degrades to the escaped fallback rather than zipping
    /// misaligned spans.
    pub fn highlight_lines_dual(
        &self,
        code: &str,
        lang: Option<&str>,
        theme_light: &str,
        theme_dark: &str,
    ) -> Result<DualHighlightedLines, HighlightError> {
        // Resolve BOTH themes up front, mirroring `highlight_lines`'
        // UnknownTheme path. Unknown lang degrades to fallback (not an error),
        // but an unknown theme name is always an error.
        let light_obj: &Theme = self
            .theme_set
            .themes
            .get(theme_light)
            .ok_or_else(|| HighlightError::UnknownTheme(theme_light.to_string()))?;
        let dark_obj: &Theme = self
            .theme_set
            .themes
            .get(theme_dark)
            .ok_or_else(|| HighlightError::UnknownTheme(theme_dark.to_string()))?;

        // Background vars are emitted whenever the theme defines one; a
        // colour-only theme (no `settings.background`) yields `None` and the
        // corresponding `--shiki-*-bg` var is simply omitted downstream.
        let light_bg = light_obj.settings.background.map(color_to_hex);
        let dark_bg = dark_obj.settings.background.map(color_to_hex);

        let syntax = self.resolve_syntax(lang);

        let Some(syntax) = syntax else {
            return Ok(dual_fallback_lines(code, light_bg, dark_bg));
        };

        // Two highlighters over the SAME resolved syntax — only the theme
        // differs, so per-line region *text* is identical between them.
        let mut h_light = HighlightLines::new(syntax, light_obj);
        let mut h_dark = HighlightLines::new(syntax, dark_obj);
        let mut lines: Vec<String> = Vec::new();
        for line in LinesWithEndings::from(code) {
            let light_regions = match h_light.highlight_line(line, &self.syntax_set) {
                Ok(r) => r,
                Err(_) => return Ok(dual_fallback_lines(code, light_bg, dark_bg)),
            };
            let dark_regions = match h_dark.highlight_line(line, &self.syntax_set) {
                Ok(r) => r,
                Err(_) => return Ok(dual_fallback_lines(code, light_bg, dark_bg)),
            };

            // Region-zip guard: the two themes must produce the same token
            // boundaries (same count, same text per token). If they don't, the
            // zip would emit misaligned spans — degrade to fallback instead.
            let aligned = light_regions.len() == dark_regions.len()
                && light_regions
                    .iter()
                    .zip(dark_regions.iter())
                    .all(|((_, lt), (_, dt))| lt == dt);
            if !aligned {
                return Ok(dual_fallback_lines(code, light_bg, dark_bg));
            }

            let mut line_html = String::new();
            for ((light_style, text), (dark_style, _)) in
                light_regions.iter().zip(dark_regions.iter())
            {
                // Spec (#1066): a dual span carries ONLY `--shiki-light` /
                // `--shiki-dark` color vars — the sole difference vs the single
                // path is those vars replacing `color:`. Syntect font styles
                // (bold/italic/underline) are intentionally NOT emitted here:
                // the two themes could disagree on style and there is no dual
                // custom-property convention for it in this primitive. Wiring
                // font styles is out of scope for this engine sub-issue.
                //
                // Escape with the SAME escaper syntect uses for text nodes so the
                // escaped output is byte-identical to the single path's token
                // text. (Verified equal to syntect's `Escape` in tests.)
                let escaped = escape_html(text);
                line_html.push_str("<span style=\"--shiki-light:");
                line_html.push_str(&color_to_hex(light_style.foreground));
                line_html.push_str(";--shiki-dark:");
                line_html.push_str(&color_to_hex(dark_style.foreground));
                line_html.push_str("\">");
                line_html.push_str(&escaped);
                line_html.push_str("</span>");
            }
            lines.push(line_html);
        }

        Ok(DualHighlightedLines {
            lines,
            light_bg,
            dark_bg,
            fallback: false,
        })
    }

    /// Highlight a code block in **class-emission mode** — every token is
    /// wrapped in a `<span class="…">` carrying a semantic *role* class (from
    /// the #1529 [`classify`] taxonomy) instead of an inline `color:` or a
    /// `--shiki-*` custom property. This is the engine primitive for
    /// `codeHighlight.mode: "class"` (Highlight Tokens epic, zfb#1528).
    ///
    /// Unlike [`Self::highlight_lines`] / [`Self::highlight_lines_dual`], this
    /// path does NOT go through syntect's `HighlightLines` (which applies a
    /// theme and discards the scope stack). Class mode needs the raw scopes,
    /// so it drives a `ParseState::parse_line` + `ScopeStack::apply` loop
    /// directly and classifies each token's scope stack.
    ///
    /// * `code` - raw source code (no surrounding HTML).
    /// * `lang` - language identifier from the markdown fence.
    /// * `prefix` - class-name prefix (e.g. `"hi-"`); the default class for a
    ///   role is `{prefix}{short_name}` (e.g. `hi-kw`).
    /// * `role_classes` - per-role class overrides keyed by the canonical full
    ///   role name (e.g. `"keyword"` → `"text-violet-600
    ///   dark:text-violet-400"`); when a role has an override its value is
    ///   emitted verbatim (attribute-escaped) instead of
    ///   `{prefix}{short_name}`.
    ///
    /// ## Cross-line scope state
    ///
    /// ONE `ParseState` and ONE `ScopeStack` are persisted across ALL lines of
    /// the block. A scope pushed on one line (an open block comment, a
    /// multi-line string, a template literal) is popped on a later line;
    /// resetting either per line would silently misclassify line 2+.
    ///
    /// ## Token emission
    ///
    /// Per token: [`classify`] the scope stack → resolved class is
    /// `role_classes[short_name]` if configured, else `{prefix}{short_name}`;
    /// emit `<span class="{escaped-class}">{escaped-text}</span>`. Adjacent
    /// tokens that resolve to the same class are MERGED into one span.
    /// Unclassified tokens (classifier returns `None`) are emitted as bare
    /// escaped text with NO wrapper span (they inherit the base foreground).
    ///
    /// ## Fallback
    ///
    /// Unknown lang or a parse/apply error mirrors [`fallback_lines`]:
    /// HTML-escaped source lines with no token spans (`fallback = true`).
    pub fn highlight_lines_classes(
        &self,
        code: &str,
        lang: Option<&str>,
        prefix: &str,
        role_classes: &BTreeMap<String, String>,
    ) -> Result<ClassHighlightedLines, HighlightError> {
        let syntax = self.resolve_syntax(lang);

        let Some(syntax) = syntax else {
            return Ok(class_fallback_lines(
                code,
                ClassHighlightFallbackReason::UnknownLanguage,
            ));
        };

        // ONE ParseState + ONE ScopeStack across ALL lines — cross-line
        // constructs (block comments, multi-line strings, template literals)
        // depend on the scope state surviving line boundaries.
        let mut state = ParseState::new(syntax);
        let mut stack = ScopeStack::new();
        let mut lines: Vec<String> = Vec::new();
        for line in LinesWithEndings::from(code) {
            let ops = match state.parse_line(line, &self.syntax_set) {
                Ok(ops) => ops,
                // Degrade to escaped fallback instead of bubbling Err so
                // callers never see a bare unclassified block.
                Err(_) => {
                    return Ok(class_fallback_lines(
                        code,
                        ClassHighlightFallbackReason::Tokenization,
                    ));
                }
            };
            // Per-line run buffer: consecutive tokens with the same resolved
            // class are merged into a single span. A run's class is
            // `Some(class)` for a classified token, `None` for an
            // unclassified (bare-text) run.
            let mut runs: Vec<(Option<String>, String)> = Vec::new();
            for (tok, op) in ScopeRegionIterator::new(&ops, line) {
                if stack.apply(op).is_err() {
                    return Ok(class_fallback_lines(
                        code,
                        ClassHighlightFallbackReason::Tokenization,
                    ));
                }
                if tok.is_empty() {
                    continue;
                }
                let resolved = classify(stack.as_slice()).map(|role| {
                    // `roleClasses` overrides are keyed by the FULL role name
                    // (`"keyword"`), matching user config / `CODE_HIGHLIGHT_ROLES`.
                    // The default class uses the short suffix (`hi-kw`). Looking
                    // the override up by `short_name` would silently miss every
                    // full-name key (zfb#1528 deep-review fix).
                    role_classes
                        .get(role.full_name())
                        .cloned()
                        .unwrap_or_else(|| format!("{prefix}{}", role.short_name()))
                });
                let escaped = escape_html(tok);
                match runs.last_mut() {
                    Some((cls, text)) if *cls == resolved => text.push_str(&escaped),
                    _ => runs.push((resolved, escaped)),
                }
            }
            let mut line_html = String::new();
            for (cls, text) in runs {
                match cls {
                    Some(class) => {
                        line_html.push_str("<span class=\"");
                        line_html.push_str(&escape_html(&class));
                        line_html.push_str("\">");
                        line_html.push_str(&text);
                        line_html.push_str("</span>");
                    }
                    None => line_html.push_str(&text),
                }
            }
            lines.push(line_html);
        }

        Ok(ClassHighlightedLines {
            lines,
            fallback: false,
            fallback_reason: None,
        })
    }

    /// Render arbitrary source in semantic class mode without constructing a
    /// Markdown fence.
    ///
    /// This is the shared facade for direct consumers and the native Markdown
    /// class-mode plugin. It validates the direct-call options, calls
    /// [`Self::highlight_lines_classes`] exactly once, then owns the canonical
    /// `<pre> → <code> → <span class="line">` wrapper markup. Unknown
    /// languages and tokenizer failures are successful, escaped fallback
    /// outcomes whose typed reason is exposed on [`ClassHighlightOutcome`].
    pub fn render_class_highlight(
        &self,
        code: &str,
        language: &str,
        class_prefix: &str,
        role_classes: &BTreeMap<String, String>,
    ) -> Result<ClassHighlightOutcome, ClassHighlightRenderError> {
        validate_class_highlight_options(language, class_prefix, role_classes)
            .map_err(ClassHighlightRenderError::Validation)?;

        let highlighted = self
            .highlight_lines_classes(code, Some(language), class_prefix, role_classes)
            .map_err(ClassHighlightRenderError::Highlight)?;
        let root_class = format!("{class_prefix}root");
        let html = render_class_highlight_markup(&root_class, &highlighted.lines);

        Ok(ClassHighlightOutcome {
            html,
            fallback_reason: highlighted.fallback_reason,
            root_class,
            lines: highlighted.lines,
        })
    }
}

/// Per-line highlighting result returned by [`Highlighter::highlight_lines`].
#[derive(Debug, Clone)]
pub struct HighlightedLines {
    /// CSS-safe theme slug (used as `syntect-{slug}` class on `<pre>`).
    pub theme_slug: String,
    /// One HTML fragment per source line from syntect.
    /// On the fallback path each entry is the HTML-escaped source line.
    pub lines: Vec<String>,
    /// `true` when the output used the themed-fallback path (unknown lang or
    /// tokenization error) rather than per-token syntect highlighting.
    pub fallback: bool,
}

/// Per-line dual-theme highlighting result returned by
/// [`Highlighter::highlight_lines_dual`].
///
/// Each token carries both a light and a dark colour as CSS custom properties
/// (`--shiki-light` / `--shiki-dark`) so a single payload renders correctly
/// under either colour scheme. The two `*_bg` fields are the per-theme
/// backgrounds (each `Option`: `None` when a theme defines no background).
#[derive(Debug, Clone)]
pub struct DualHighlightedLines {
    /// One HTML fragment per source line. On the highlighted path each token is
    /// `<span style="--shiki-light:#…;--shiki-dark:#…">{escaped}</span>`; on the
    /// fallback path each entry is the HTML-escaped source line (no colour vars).
    pub lines: Vec<String>,
    /// Light theme background as `#rrggbb`, or `None` when the theme defines no
    /// `settings.background` (the `--shiki-light-bg` var is then omitted).
    pub light_bg: Option<String>,
    /// Dark theme background as `#rrggbb`, or `None` when the theme defines no
    /// `settings.background` (the `--shiki-dark-bg` var is then omitted).
    pub dark_bg: Option<String>,
    /// `true` when the output used the themed-fallback path (unknown lang,
    /// tokenization error, or a per-line region-alignment mismatch) rather than
    /// per-token dual highlighting.
    pub fallback: bool,
}

/// Per-line class-mode highlighting result returned by
/// [`Highlighter::highlight_lines_classes`].
///
/// Each token is `<span class="…">{escaped}</span>` carrying a semantic role
/// class (or bare escaped text for unclassified tokens). Unlike
/// [`HighlightedLines`] there is no `theme_slug`: class mode is theme-agnostic
/// (colours come from the consumer's CSS keyed on the role classes), and the
/// `<pre>` wrapper is classed `{prefix}root` by the plugin, not `syntect-{slug}`.
#[derive(Debug, Clone)]
pub struct ClassHighlightedLines {
    /// One HTML fragment per source line. On the highlighted path each token is
    /// a role-classed `<span>` (adjacent same-class tokens merged) or bare
    /// escaped text; on the fallback path each entry is the HTML-escaped source
    /// line with no spans.
    pub lines: Vec<String>,
    /// `true` when the output used the escaped-fallback path (unknown lang or a
    /// parse/apply error) rather than per-token class highlighting.
    pub fallback: bool,
    /// The exact escaped-fallback cause, when [`Self::fallback`] is true.
    ///
    /// This supplements the legacy boolean so direct consumers can distinguish
    /// an unsupported language from a tokenizer failure without attempting to
    /// inspect the generated HTML.
    pub fallback_reason: Option<ClassHighlightFallbackReason>,
}

/// Why a class-highlight operation produced escaped source instead of role
/// spans. These are expected outcomes, not traps or validation errors.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ClassHighlightFallbackReason {
    /// No bundled syntax or supported alias matched the supplied non-empty
    /// language token.
    UnknownLanguage,
    /// Syntect could not parse a line or apply its scope operations.
    Tokenization,
}

/// Result of [`Highlighter::render_class_highlight`].
///
/// `html` is the ready-to-emit semantic wrapper used by direct consumers. The
/// native Markdown plugin uses the crate-private line and root-class accessors
/// to preserve its structured HAST nodes for downstream code enrichment while
/// sharing this renderer's tokenization, validation, fallback, and wrapper
/// contract.
#[derive(Debug, Clone)]
pub struct ClassHighlightOutcome {
    /// Complete escaped HTML:
    /// `<pre class="{prefix}root"><code><span class="line">…`.
    pub html: String,
    /// `None` for tokenized output; otherwise the expected fallback cause.
    pub fallback_reason: Option<ClassHighlightFallbackReason>,
    root_class: String,
    lines: Vec<String>,
}

impl ClassHighlightOutcome {
    /// Root `<pre>` class for the native structured-HAST adapter.
    #[must_use]
    pub(crate) fn root_class(&self) -> &str {
        &self.root_class
    }

    /// Per-source-line HTML fragments for the native structured-HAST adapter.
    #[must_use]
    pub(crate) fn into_lines(self) -> Vec<String> {
        self.lines
    }
}

/// Invalid direct class-highlight options.
///
/// Native `zfb` config prefixes these field-oriented messages with
/// `codeHighlight.` while retaining theme mutual-exclusion and Tailwind policy
/// validation in its own layer.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClassHighlightValidationError {
    /// The direct facade requires a language; Markdown blocks without a
    /// language remain outside the syntect plugin as before.
    EmptyLanguage,
    /// The prefix would not be a valid semantic class-name prefix.
    InvalidClassPrefix { prefix: String },
    /// A role override did not use a canonical full role name.
    UnknownRole { role: String },
    /// An override would collide with the Markdown line-wrapper class.
    LineClassCollision { role: String, class: String },
}

impl std::fmt::Display for ClassHighlightValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EmptyLanguage => write!(f, "language must be non-empty"),
            Self::InvalidClassPrefix { prefix } => write!(
                f,
                "classPrefix {prefix:?} must be non-empty and match /^[A-Za-z][A-Za-z0-9_-]*$/"
            ),
            Self::UnknownRole { role } => write!(
                f,
                "roleClasses key {role:?} is not a known role; valid roles are: {}",
                crate::hi_roles::HiRole::FULL_NAMES.join(", ")
            ),
            Self::LineClassCollision { role, class } => write!(
                f,
                "roleClasses[{role:?}] value {class:?} must not contain the token \"line\" (collides with the code-enrichment line wrapper class)"
            ),
        }
    }
}

impl std::error::Error for ClassHighlightValidationError {}

/// Error from [`Highlighter::render_class_highlight`].
#[derive(Debug, thiserror::Error)]
pub enum ClassHighlightRenderError {
    /// The caller supplied invalid class-highlight options.
    #[error(transparent)]
    Validation(#[from] ClassHighlightValidationError),
    /// An unexpected highlighter-level error. Normal unknown-language and
    /// tokenization cases are represented by [`ClassHighlightOutcome`], not
    /// this error.
    #[error(transparent)]
    Highlight(#[from] HighlightError),
}

/// Validate class-prefix and role-override values shared by native config and
/// the direct arbitrary-code facade.
pub fn validate_class_highlight_classes(
    class_prefix: &str,
    role_classes: &BTreeMap<String, String>,
) -> Result<(), ClassHighlightValidationError> {
    if !is_valid_class_prefix(class_prefix) {
        return Err(ClassHighlightValidationError::InvalidClassPrefix {
            prefix: class_prefix.to_string(),
        });
    }
    for key in role_classes.keys() {
        if !crate::hi_roles::HiRole::FULL_NAMES.contains(&key.as_str()) {
            return Err(ClassHighlightValidationError::UnknownRole { role: key.clone() });
        }
    }
    for (role, class) in role_classes {
        if class.split_whitespace().any(|token| token == "line") {
            return Err(ClassHighlightValidationError::LineClassCollision {
                role: role.clone(),
                class: class.clone(),
            });
        }
    }
    Ok(())
}

/// Validate direct arbitrary-code class-highlight options.
///
/// Unlike fenced Markdown, a direct call has no meaningful no-language mode,
/// so an empty language is rejected instead of being silently treated as
/// unhighlighted text.
pub fn validate_class_highlight_options(
    language: &str,
    class_prefix: &str,
    role_classes: &BTreeMap<String, String>,
) -> Result<(), ClassHighlightValidationError> {
    if language.is_empty() {
        return Err(ClassHighlightValidationError::EmptyLanguage);
    }
    validate_class_highlight_classes(class_prefix, role_classes)
}

impl Default for Highlighter {
    fn default() -> Self {
        Self::new()
    }
}

/// Map a language tag to one or more candidate syntect syntax names, in order
/// of preference. The first one that exists in the loaded `SyntaxSet` wins.
///
/// Multiple candidates preserve useful highlighting if an older generated
/// dump is accidentally paired with newer alias code.
fn resolve_alias(lang: &str) -> &'static [&'static str] {
    match lang {
        "ts" | "typescript" => &["TypeScript", "JavaScript"],
        "tsx" => &["TypeScriptReact", "TypeScript", "JavaScript"],
        "js" | "javascript" => &["JavaScript"],
        "jsx" => &["JavaScript"],
        "rs" | "rust" => &["Rust"],
        "py" | "python" => &["Python"],
        "sh" | "bash" | "zsh" => &["Bourne Again Shell (bash)", "Bash"],
        "md" | "markdown" => &["Markdown"],
        // mdx has no dedicated grammar; treat as Markdown so fences get theming
        "mdx" => &["Markdown"],
        "yaml" | "yml" => &["YAML"],
        "json" => &["JSON"],
        "c" => &["C"],
        "cpp" | "c++" => &["C++"],
        "go" => &["Go"],
        "toml" => &["TOML"],
        "html" => &["HTML"],
        "css" => &["CSS"],
        _ => &[],
    }
}

/// Lowercase + collapse non-alphanumerics to `-` (no leading/trailing dashes,
/// no doubled dashes).
fn theme_slug(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut last_dash = true; // suppress leading dash
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            for c in ch.to_lowercase() {
                out.push(c);
            }
            last_dash = false;
        } else if !last_dash {
            out.push('-');
            last_dash = true;
        }
    }
    if out.ends_with('-') {
        out.pop();
    }
    out
}

/// Build a [`HighlightedLines`] for the fallback path (unknown lang or
/// tokenization error). Splits `code` on `LinesWithEndings` so the per-line
/// vector has the same granularity as the normal path.
fn fallback_lines(code: &str, slug: &str) -> HighlightedLines {
    let lines: Vec<String> = LinesWithEndings::from(code).map(escape_html).collect();
    HighlightedLines {
        theme_slug: slug.to_string(),
        lines,
        fallback: true,
    }
}

/// Format a syntect [`Color`] as a lowercase `#rrggbb` string, dropping alpha.
///
/// Matches the RGB branch of syntect's own `write_css_color`
/// (`#{:02x}{:02x}{:02x}`) so the colours emitted in `--shiki-*` vars are
/// byte-identical to what the single `color:` path would emit — minus the alpha
/// channel, which is intentionally dropped for the dual custom-property form.
fn color_to_hex(c: Color) -> String {
    format!("#{:02x}{:02x}{:02x}", c.r, c.g, c.b)
}

/// Build a [`DualHighlightedLines`] for the dual fallback path (unknown lang,
/// tokenization error, or region-alignment mismatch). Splits `code` on
/// `LinesWithEndings` so the per-line vector matches the normal path's
/// granularity; each line is HTML-escaped with no colour vars. Background vars
/// are preserved (the themes resolved fine; only tokenization fell back).
fn dual_fallback_lines(
    code: &str,
    light_bg: Option<String>,
    dark_bg: Option<String>,
) -> DualHighlightedLines {
    let lines: Vec<String> = LinesWithEndings::from(code).map(escape_html).collect();
    DualHighlightedLines {
        lines,
        light_bg,
        dark_bg,
        fallback: true,
    }
}

/// Build a [`ClassHighlightedLines`] for the class-mode fallback path (unknown
/// lang or a parse/apply error). Splits `code` on `LinesWithEndings` so the
/// per-line vector matches the normal path's granularity; each line is
/// HTML-escaped with no token spans.
fn class_fallback_lines(code: &str, reason: ClassHighlightFallbackReason) -> ClassHighlightedLines {
    let lines: Vec<String> = LinesWithEndings::from(code).map(escape_html).collect();
    ClassHighlightedLines {
        lines,
        fallback: true,
        fallback_reason: Some(reason),
    }
}

/// Render the class-mode wrapper around already escaped per-line fragments.
///
/// This is intentionally separate from syntax tokenization: direct callers
/// receive its exact HTML, while the Markdown plugin receives the same line
/// fragments to retain structured HAST nodes for code-enrichment visitors.
fn render_class_highlight_markup(root_class: &str, lines: &[String]) -> String {
    let mut html = String::with_capacity(
        root_class.len()
            + lines.iter().map(String::len).sum::<usize>()
            + lines.len() * "<span class=\"line\"></span>".len()
            + "<pre class=\"\"><code></code></pre>".len(),
    );
    html.push_str("<pre class=\"");
    html.push_str(&escape_html(root_class));
    html.push_str("\"><code>");
    for line in lines {
        html.push_str("<span class=\"line\">");
        html.push_str(line);
        html.push_str("</span>");
    }
    html.push_str("</code></pre>");
    html
}

/// `classPrefix` validation: non-empty, first char an ASCII letter, remaining
/// chars ASCII alphanumeric, `_`, or `-`.
fn is_valid_class_prefix(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

/// Errors returned by the highlighter.
#[derive(Debug, thiserror::Error)]
pub enum HighlightError {
    #[error("unknown theme: {0}")]
    UnknownTheme(String),
    #[error("theme load io error: {0}")]
    ThemeLoad(#[from] std::io::Error),
    #[error("theme parse error: {0}")]
    ThemeParse(String),
    /// A single `.tmTheme` file failed to parse; carries path + message.
    #[error("theme parse error in {0}")]
    ThemeFileParse(ThemeFileError),
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verify that [`BUNDLED_SYNTAX_SET`] and [`BUNDLED_THEME_SET`] are shared
    /// across `Highlighter` instances rather than re-deserialized on every
    /// construction. Two `Highlighter::new()` calls must return the same `Arc`
    /// pointer for the syntax set, proving the `LazyLock` fires only once per
    /// process.
    #[test]
    fn bundled_sets_are_shared_across_highlighter_instances() {
        let h1 = Highlighter::new();
        let h2 = Highlighter::new();
        // Arc::ptr_eq compares the underlying data pointer — same address means
        // the same allocation was reused, i.e. deserialization happened once.
        assert!(
            Arc::ptr_eq(&h1.syntax_set, &h2.syntax_set),
            "BUNDLED_SYNTAX_SET must be shared across Highlighter instances (LazyLock fired twice)"
        );
        // ThemeSet is cloned per-instance (so user themes don't bleed across
        // pipelines), but both must contain the same bundled theme names.
        let names1 = h1.theme_names();
        let names2 = h2.theme_names();
        assert_eq!(
            names1, names2,
            "bundled theme names must be identical across Highlighter instances"
        );
    }

    #[test]
    fn theme_names_includes_builtins() {
        let h = Highlighter::new();
        let names = h.theme_names();
        for expected in [
            "base16-ocean.dark",
            "base16-ocean.light",
            "InspiredGitHub",
            "Solarized (dark)",
            "Solarized (light)",
        ] {
            assert!(
                names.iter().any(|n| n == expected),
                "missing built-in theme `{expected}`; got: {names:?}"
            );
        }
    }

    #[test]
    fn highlight_rust_snippet_has_pre_and_code() {
        let h = Highlighter::new();
        let html = h
            .highlight("fn main() {}\n", Some("rust"), None)
            .expect("highlight ok");
        assert!(
            html.contains("<pre class=\"syntect-"),
            "missing pre class: {html}"
        );
        assert!(html.contains("<code>"), "missing <code>: {html}");
        assert!(html.contains("</code></pre>"), "missing closer: {html}");
    }

    #[test]
    fn unknown_language_falls_back() {
        let h = Highlighter::new();
        let html = h
            .highlight("hello", Some("klingon"), None)
            .expect("fallback ok");
        // Unknown lang uses the themed wrapper, not bare <pre><code>
        assert!(
            html.starts_with("<pre class=\"syntect-"),
            "expected themed wrapper: {html}"
        );
        assert!(html.contains("hello"), "code content missing: {html}");
    }

    #[test]
    fn fallback_escapes_html() {
        let h = Highlighter::new();
        let html = h
            .highlight("<script>alert(1)</script>", Some("klingon"), None)
            .expect("fallback ok");
        assert!(html.contains("&lt;script&gt;"), "not escaped: {html}");
        assert!(
            html.contains("&lt;/script&gt;"),
            "closing not escaped: {html}"
        );
        assert!(!html.contains("<script>"), "raw script leaked: {html}");
    }

    #[test]
    fn set_default_theme_rejects_unknown() {
        let mut h = Highlighter::new();
        let err = h.set_default_theme("nonexistent").unwrap_err();
        match err {
            HighlightError::UnknownTheme(name) => assert_eq!(name, "nonexistent"),
            other => unreachable!("expected UnknownTheme, got {other:?}"),
        }
    }

    #[test]
    fn alias_ts_highlights_as_typescript() {
        let h = Highlighter::new();
        let html = h
            .highlight("const x: number = 1;\n", Some("ts"), None)
            .expect("highlight ok");
        let js = h
            .highlight("const x: number = 1;\n", Some("js"), None)
            .expect("javascript highlight ok");
        assert!(
            html.starts_with("<pre class=\"syntect-"),
            "unexpected wrapper: {html}"
        );
        assert!(html.contains("<span"), "no syntect spans: {html}");
        assert_ne!(html, "<pre><code>const x: number = 1;\n</code></pre>");
        assert_ne!(
            html, js,
            "ts must use the TypeScript grammar, not JavaScript"
        );
    }

    #[test]
    fn empty_code_with_known_lang_returns_empty_pre_code() {
        let h = Highlighter::new();
        let html = h.highlight("", Some("rust"), None).expect("highlight ok");
        assert!(
            html.starts_with("<pre class=\"syntect-"),
            "missing pre class: {html}"
        );
        assert!(
            html.contains("<code></code>") || html.ends_with("<code></code></pre>"),
            "expected empty <code> body: {html}"
        );
    }

    #[test]
    fn empty_lang_falls_back_to_safe_pre_code() {
        let h = Highlighter::new();
        let html = h.highlight("x = 1", Some(""), None).expect("highlight ok");
        // Empty lang uses the themed wrapper now
        assert!(
            html.starts_with("<pre class=\"syntect-"),
            "expected themed wrapper for empty lang: {html}"
        );
        assert!(html.contains("x = 1"), "code content missing: {html}");
    }

    #[test]
    fn empty_theme_uses_default() {
        let h = Highlighter::new();
        let with_default = h
            .highlight("fn main() {}\n", Some("rust"), None)
            .expect("default ok");
        let with_empty = h
            .highlight("fn main() {}\n", Some("rust"), Some(""))
            .expect("empty-theme ok");
        assert_eq!(with_default, with_empty);
    }

    #[test]
    fn theme_override_changes_class_slug() {
        let h = Highlighter::new();
        let default = h
            .highlight("fn main() {}\n", Some("rust"), None)
            .expect("default ok");
        let override_html = h
            .highlight("fn main() {}\n", Some("rust"), Some("InspiredGitHub"))
            .expect("override ok");
        assert!(default.contains("syntect-base16-ocean-dark"));
        assert!(override_html.contains("syntect-inspiredgithub"));
        assert_ne!(default, override_html);
    }

    // --- New tests for alias resolution and themed fallback ---

    #[test]
    fn mdx_alias_resolves_to_markdown() {
        let h = Highlighter::new();
        let html = h
            .highlight("# h\n", Some("mdx"), None)
            .expect("mdx highlight ok");
        // mdx maps to Markdown, which has a grammar — should produce spans
        assert!(
            html.starts_with("<pre class=\"syntect-"),
            "expected themed wrapper: {html}"
        );
        assert!(
            html.contains("<span"),
            "expected spans for mdx/Markdown: {html}"
        );
    }

    #[test]
    fn tsx_jsx_keep_working() {
        let h = Highlighter::new();
        let tsx_html = h
            .highlight("const x: number = 1;\n", Some("tsx"), None)
            .expect("tsx ok");
        assert!(
            tsx_html.starts_with("<pre class=\"syntect-"),
            "tsx: expected themed wrapper: {tsx_html}"
        );
        assert!(
            tsx_html.contains("<span"),
            "tsx: expected spans: {tsx_html}"
        );
        let js_html = h
            .highlight("const x: number = 1;\n", Some("js"), None)
            .expect("js ok");
        assert_ne!(
            tsx_html, js_html,
            "tsx must use the TypeScriptReact grammar, not JavaScript"
        );

        let jsx_html = h
            .highlight("const x = 1;\n", Some("jsx"), None)
            .expect("jsx ok");
        assert!(
            jsx_html.starts_with("<pre class=\"syntect-"),
            "jsx: expected themed wrapper: {jsx_html}"
        );
        assert!(
            jsx_html.contains("<span"),
            "jsx: expected spans: {jsx_html}"
        );
    }

    #[test]
    fn unknown_language_uses_themed_wrapper() {
        let h = Highlighter::new();
        let html = h
            .highlight("hello world", Some("klingon"), None)
            .expect("klingon fallback ok");
        assert!(
            html.starts_with("<pre class=\"syntect-base16-ocean-dark\">"),
            "expected themed wrapper with default theme: {html}"
        );
        assert!(
            html.contains("<code>hello world</code>"),
            "code content: {html}"
        );
        assert!(!html.contains("<span"), "no spans for unknown lang: {html}");
    }

    #[test]
    fn empty_lang_uses_themed_wrapper() {
        let h = Highlighter::new();
        // Some("") — treated as no language
        let html_empty = h.highlight("code", Some(""), None).expect("empty lang ok");
        assert!(
            html_empty.starts_with("<pre class=\"syntect-"),
            "Some(\"\") must use themed wrapper: {html_empty}"
        );
        // None — no language at all
        let html_none = h.highlight("code", None, None).expect("none lang ok");
        assert!(
            html_none.starts_with("<pre class=\"syntect-"),
            "None lang must use themed wrapper: {html_none}"
        );
    }

    #[test]
    fn themed_fallback_escapes_html() {
        let h = Highlighter::new();
        let html = h
            .highlight("<script>alert(1)</script>", Some("klingon"), None)
            .expect("themed fallback escape ok");
        assert!(
            html.starts_with("<pre class=\"syntect-"),
            "expected themed wrapper: {html}"
        );
        assert!(html.contains("&lt;script&gt;"), "< not escaped: {html}");
        assert!(html.contains("&lt;/script&gt;"), "</ not escaped: {html}");
        assert!(!html.contains("<script>"), "raw script leaked: {html}");
    }

    /// Path B: tokenization errors fall back to themed output.
    ///
    /// Note: the bundled syntect grammars do not have an easily-reproducible
    /// per-line tokenization error with a synthetic input, so this test
    /// verifies the happy path still produces themed output (no regression)
    /// and that the function signature change did not break compilation.
    /// A more targeted test would require a custom grammar that errors
    /// mid-stream, which is out of scope for bundled-syntax testing.
    #[test]
    fn tokenization_error_path_does_not_bubble_err() {
        // The important property is that highlight() never returns Err due to
        // tokenization; it degrades to the themed fallback instead.
        let h = Highlighter::new();
        // Normal highlighted path — must still succeed
        let html = h
            .highlight("fn main() {}\n", Some("rust"), None)
            .expect("rust highlight must not return Err");
        assert!(
            html.starts_with("<pre class=\"syntect-"),
            "highlight must produce themed output: {html}"
        );
    }

    #[test]
    fn list_builtin_syntax_names_includes_expected_aliases() {
        // Verify the alias targets actually exist in the CUSTOM bundled
        // SyntaxSet (issue #1848's dump, not syntect's raw
        // `load_defaults_newlines()`) so resolve_alias never maps to a name
        // that isn't there.
        let ss = bundled_syntax_set_for_tests();
        let names: Vec<&str> = ss.syntaxes().iter().map(|s| s.name.as_str()).collect();
        for expected in [
            "Markdown",
            "JavaScript",
            "Rust",
            "Python",
            "YAML",
            "JSON",
            "C",
            "C++",
            "Go",
            "HTML",
            "CSS",
            "TOML",
            "TypeScript",
            "TypeScriptReact",
        ] {
            assert!(
                names.contains(&expected),
                "bundled SyntaxSet missing expected alias target: {expected}\navailable: {names:?}"
            );
        }
        // Bash may appear under either canonical name
        assert!(
            names
                .iter()
                .any(|n| *n == "Bourne Again Shell (bash)" || *n == "Bash"),
            "bundled SyntaxSet missing Bash syntax; available: {names:?}"
        );
    }

    /// TOML fences now highlight via the custom dump's grammar instead of
    /// degrading to the escaped fallback (issue #1848).
    #[test]
    fn alias_toml_highlights_with_real_grammar() {
        let h = Highlighter::new();
        let html = h
            .highlight("[package]\nname = \"zfb\"\n", Some("toml"), None)
            .expect("highlight ok");
        assert!(
            html.starts_with("<pre class=\"syntect-"),
            "unexpected wrapper: {html}"
        );
        assert!(html.contains("<span"), "no syntect spans: {html}");
        assert_ne!(
            html, "<pre><code>[package]\nname = \"zfb\"\n</code></pre>",
            "toml must no longer fall back to the plain escaped-text path"
        );
    }

    // Minimal valid `.tmTheme` plist used by the load_themes_from_dir tests.
    // The `name` key determines the theme name reported by theme_names().
    const MINIMAL_TMTHEME: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>My Custom Theme</string>
    <key>settings</key>
    <array>
        <dict>
            <key>settings</key>
            <dict>
                <key>background</key>
                <string>#1e1e1e</string>
                <key>foreground</key>
                <string>#d4d4d4</string>
            </dict>
        </dict>
    </array>
    <key>uuid</key>
    <string>aaaaaaaa-0000-0000-0000-000000000001</string>
</dict>
</plist>"#;

    #[test]
    fn load_themes_from_dir_adds_custom_theme() {
        let dir = tempfile::tempdir().expect("tempdir");
        std::fs::write(dir.path().join("my-custom.tmTheme"), MINIMAL_TMTHEME)
            .expect("write fixture");

        let mut h = Highlighter::new();
        // Before loading: custom theme is absent.
        assert!(
            !h.theme_names().iter().any(|n| n == "My Custom Theme"),
            "custom theme must not be present before load"
        );

        h.load_themes_from_dir(dir.path())
            .expect("load_themes_from_dir ok");

        // After loading: custom theme is present.
        assert!(
            h.theme_names().iter().any(|n| n == "My Custom Theme"),
            "custom theme must be present after load; got: {:?}",
            h.theme_names()
        );
    }

    #[test]
    fn load_themes_from_dir_missing_dir_returns_error() {
        let mut h = Highlighter::new();
        let missing = std::path::Path::new("/tmp/zfb-test-nonexistent-themes-dir-abc123");
        let result = h.load_themes_from_dir(missing);
        assert!(
            result.is_err(),
            "expected error for missing directory, got Ok"
        );
    }

    #[test]
    fn load_themes_from_dir_invalid_tmtheme_surfaces_path_in_error() {
        let dir = tempfile::tempdir().expect("tempdir");
        // Write broken XML that can't parse as a valid plist/theme.
        std::fs::write(dir.path().join("broken.tmTheme"), b"NOT VALID XML <<<<<")
            .expect("write broken fixture");

        let mut h = Highlighter::new();
        let err = h
            .load_themes_from_dir(dir.path())
            .expect_err("must fail for broken .tmTheme");
        let msg = err.to_string();
        assert!(
            msg.contains("broken.tmTheme"),
            "error message must include filename; got: {msg}"
        );
    }

    #[test]
    fn load_themes_from_dir_non_tmtheme_files_are_skipped() {
        let dir = tempfile::tempdir().expect("tempdir");
        // Write a .txt file that would fail to parse — must be silently ignored.
        std::fs::write(dir.path().join("readme.txt"), b"NOT A THEME")
            .expect("write non-theme file");
        std::fs::write(dir.path().join("my-custom.tmTheme"), MINIMAL_TMTHEME)
            .expect("write fixture");

        let mut h = Highlighter::new();
        h.load_themes_from_dir(dir.path())
            .expect("must not fail; non-.tmTheme files are skipped");
        assert!(
            h.theme_names().iter().any(|n| n == "My Custom Theme"),
            "custom theme present after mixed-dir load"
        );
    }

    // ── Dual-theme highlighting (highlight_lines_dual) ─────────────────────

    #[test]
    fn dual_highlight_rust_emits_shiki_vars_no_color() {
        let h = Highlighter::new();
        let result = h
            .highlight_lines_dual(
                "fn main() {}\n",
                Some("rust"),
                "base16-ocean.light",
                "base16-ocean.dark",
            )
            .expect("dual highlight ok");
        assert!(
            !result.fallback,
            "should be the highlighted path, not fallback"
        );
        let html = result.lines.concat();
        assert!(
            html.contains("--shiki-light:#"),
            "missing --shiki-light var: {html}"
        );
        assert!(
            html.contains("--shiki-dark:#"),
            "missing --shiki-dark var: {html}"
        );
        // The whole point: no inline `color:` — dual mode uses custom props.
        assert!(
            !html.contains("color:#"),
            "dual path must not emit inline color: {html}"
        );
    }

    #[test]
    fn dual_highlight_backgrounds_present_and_differ() {
        let h = Highlighter::new();
        let result = h
            .highlight_lines_dual(
                "fn main() {}\n",
                Some("rust"),
                "base16-ocean.light",
                "base16-ocean.dark",
            )
            .expect("dual highlight ok");
        let light = result.light_bg.expect("light bg present");
        let dark = result.dark_bg.expect("dark bg present");
        assert!(
            light.starts_with('#') && light.len() == 7,
            "light bg not #rrggbb: {light}"
        );
        assert!(
            dark.starts_with('#') && dark.len() == 7,
            "dark bg not #rrggbb: {dark}"
        );
        assert_ne!(light, dark, "light and dark backgrounds must differ");
    }

    /// Region-alignment guard: highlighting the same syntax under two themes
    /// yields region lists whose text slices concatenate to identical per-line
    /// text, and whose token count + text match the single path's regions.
    #[test]
    fn dual_region_text_aligns_and_matches_single_path() {
        let h = Highlighter::new();
        let code = "let x: i32 = 1 + 2;\nfn f() {}\n";
        let syntax = h
            .syntax_set
            .find_syntax_by_name("Rust")
            .expect("Rust syntax present");

        let mut h_single = HighlightLines::new(syntax, &h.theme_set.themes["base16-ocean.dark"]);
        let mut h_light = HighlightLines::new(syntax, &h.theme_set.themes["base16-ocean.light"]);
        let mut h_dark = HighlightLines::new(syntax, &h.theme_set.themes["base16-ocean.dark"]);

        for line in LinesWithEndings::from(code) {
            let single = h_single.highlight_line(line, &h.syntax_set).unwrap();
            let light = h_light.highlight_line(line, &h.syntax_set).unwrap();
            let dark = h_dark.highlight_line(line, &h.syntax_set).unwrap();

            // light/dark region text slices concatenate to identical text.
            let light_text: String = light.iter().map(|(_, t)| *t).collect();
            let dark_text: String = dark.iter().map(|(_, t)| *t).collect();
            assert_eq!(
                light_text, dark_text,
                "light/dark per-line region text must be identical"
            );

            // token count + text match the single path's regions.
            assert_eq!(
                light.len(),
                single.len(),
                "dual region count must match single path"
            );
            for ((_, lt), (_, st)) in light.iter().zip(single.iter()) {
                assert_eq!(lt, st, "dual region text must match single path");
            }
        }
    }

    /// Escaping parity (codex #2): the dual path escapes token text identically
    /// to the single path. Verified two ways:
    /// 1. our `escape_html` matches syntect's own `Escape` for the same input;
    /// 2. the dual HTML's token text equals the single path's token text for a
    ///    snippet containing `& < > " '`.
    #[test]
    fn dual_escaping_matches_single_path() {
        use syntect::html::styled_line_to_highlighted_html;
        use syntect::html::IncludeBackground;

        // 1. escape_html ≡ syntect Escape for the tricky characters.
        for sample in ["& < > \" '", "a&b<c>d\"e'f", "<script>alert(1)</script>"] {
            let ours = escape_html(sample);
            // syntect's Escape is applied via styled_line_to_highlighted_html; we
            // reproduce its text-node escaping by passing a single trivial token.
            let style = syntect::highlighting::Style::default();
            let single = styled_line_to_highlighted_html(&[(style, sample)], IncludeBackground::No)
                .expect("single html ok");
            // The span wraps the escaped text; extract the inner text node.
            let inner = single
                .strip_prefix(&format!(
                    "<span style=\"color:#{:02x}{:02x}{:02x};\">",
                    style.foreground.r, style.foreground.g, style.foreground.b
                ))
                .and_then(|s| s.strip_suffix("</span>"))
                .expect("span shape");
            assert_eq!(
                ours, inner,
                "escape_html must match syntect Escape for {sample:?}"
            );
        }

        // 2. End-to-end: a snippet with special chars produces the same escaped
        // token text in dual mode as the single path emits.
        let h = Highlighter::new();
        let code = "let s = \"a & b < c > d ' e\";\n";
        let dual = h
            .highlight_lines_dual(
                code,
                Some("rust"),
                "base16-ocean.light",
                "base16-ocean.dark",
            )
            .expect("dual ok");
        let dual_html = dual.lines.concat();
        // The escaped entities must appear; raw specials must not leak.
        for needle in ["&amp;", "&lt;", "&gt;", "&quot;", "&#39;"] {
            assert!(
                dual_html.contains(needle),
                "dual output missing escaped {needle}: {dual_html}"
            );
        }
        assert!(
            !dual_html.contains(" & "),
            "raw ampersand leaked: {dual_html}"
        );
    }

    #[test]
    fn dual_missing_background_omits_bg_var() {
        // Build a Highlighter whose dark theme has no settings.background.
        let mut h = Highlighter::new();
        let mut no_bg = h.theme_set.themes["base16-ocean.dark"].clone();
        no_bg.settings.background = None;
        h.theme_set.themes.insert("no-bg-theme".to_string(), no_bg);

        let result = h
            .highlight_lines_dual(
                "fn main() {}\n",
                Some("rust"),
                "base16-ocean.light",
                "no-bg-theme",
            )
            .expect("dual highlight must not error on missing background");
        assert!(
            result.light_bg.is_some(),
            "light bg should still be present"
        );
        assert!(
            result.dark_bg.is_none(),
            "dark bg must be omitted when theme has no background"
        );
    }

    #[test]
    fn dual_unknown_theme_errors() {
        let h = Highlighter::new();
        // Unknown light theme.
        let err = h
            .highlight_lines_dual("x", Some("rust"), "no-such-theme", "base16-ocean.dark")
            .unwrap_err();
        match err {
            HighlightError::UnknownTheme(name) => assert_eq!(name, "no-such-theme"),
            other => unreachable!("expected UnknownTheme for light, got {other:?}"),
        }
        // Unknown dark theme.
        let err = h
            .highlight_lines_dual("x", Some("rust"), "base16-ocean.light", "no-such-theme")
            .unwrap_err();
        match err {
            HighlightError::UnknownTheme(name) => assert_eq!(name, "no-such-theme"),
            other => unreachable!("expected UnknownTheme for dark, got {other:?}"),
        }
    }

    #[test]
    fn dual_unknown_lang_falls_back_no_color_vars() {
        let h = Highlighter::new();
        let result = h
            .highlight_lines_dual(
                "<hello> & 'world'\n",
                Some("klingon"),
                "base16-ocean.light",
                "base16-ocean.dark",
            )
            .expect("fallback ok");
        assert!(result.fallback, "unknown lang must set fallback = true");
        let html = result.lines.concat();
        assert!(
            !html.contains("--shiki-light:"),
            "fallback must not emit color vars: {html}"
        );
        assert!(
            !html.contains("<span"),
            "fallback must be plain text: {html}"
        );
        // Escaped, not raw.
        assert!(
            html.contains("&lt;hello&gt;"),
            "fallback not escaped: {html}"
        );
        assert!(html.contains("&amp;"), "fallback amp not escaped: {html}");
        assert!(
            html.contains("&#39;world&#39;"),
            "fallback quote not escaped: {html}"
        );
        // Backgrounds still resolved (themes were valid).
        assert!(result.light_bg.is_some() && result.dark_bg.is_some());
    }

    #[test]
    fn color_to_hex_matches_syntect_rgb_format() {
        // color_to_hex must produce the same `#rrggbb` lowercase form syntect's
        // write_css_color emits for the alpha==0xFF case (alpha dropped).
        let c = Color {
            r: 0xd0,
            g: 0x87,
            b: 0x70,
            a: 0xff,
        };
        assert_eq!(color_to_hex(c), "#d08770");
        // Alpha is dropped even when not opaque.
        let c2 = Color {
            r: 0x01,
            g: 0x02,
            b: 0x03,
            a: 0x80,
        };
        assert_eq!(color_to_hex(c2), "#010203");
    }

    // ── Class-emission highlighting (highlight_lines_classes) ──────────────

    /// A rust snippet in class mode carries role classes (`hi-kw` / `hi-str`)
    /// and NEVER any inline colour form (`style=` / `color:#` / `--shiki-`).
    #[test]
    fn class_mode_rust_emits_role_classes_no_inline_style() {
        let h = Highlighter::new();
        let result = h
            .highlight_lines_classes(
                "fn main() {\n    let s = \"hi\";\n}\n",
                Some("rust"),
                "hi-",
                &BTreeMap::new(),
            )
            .expect("class highlight ok");
        assert!(!result.fallback, "known lang must not fall back");
        let html = result.lines.concat();
        assert!(html.contains("class=\"hi-kw\""), "missing hi-kw: {html}");
        assert!(html.contains("class=\"hi-str\""), "missing hi-str: {html}");
        assert!(
            !html.contains("style="),
            "must not emit inline style: {html}"
        );
        assert!(
            !html.contains("color:#"),
            "must not emit inline color: {html}"
        );
        assert!(
            !html.contains("--shiki-"),
            "must not emit shiki vars: {html}"
        );
    }

    /// The cross-line coverage check: a block comment and a string literal
    /// each spanning two source lines must classify line-2 content correctly.
    /// This only holds because ONE `ParseState` and ONE `ScopeStack` persist
    /// across the newline — resetting either would misclassify line 2+.
    #[test]
    fn class_mode_multiline_block_comment_and_string_classify_line2() {
        let h = Highlighter::new();
        let block = h
            .highlight_lines_classes("/* c1\n c2 */\n", Some("rust"), "hi-", &BTreeMap::new())
            .expect("ok");
        assert_eq!(block.lines.len(), 2, "two source lines");
        assert!(
            block.lines[1].contains("class=\"hi-com\""),
            "line 2 of block comment must be hi-com: {:?}",
            block.lines[1]
        );

        let string = h
            .highlight_lines_classes(
                "let y = \"m1\nm2\";\n",
                Some("rust"),
                "hi-",
                &BTreeMap::new(),
            )
            .expect("ok");
        assert_eq!(string.lines.len(), 2, "two source lines");
        assert!(
            string.lines[1].contains("class=\"hi-str\""),
            "line 2 of multi-line string must be hi-str: {:?}",
            string.lines[1]
        );
    }

    /// Escaping corpus (mirrors `dual_escaping_matches_single_path`): the same
    /// tricky characters (`& < > " '`) must appear escaped in class output and
    /// never leak raw.
    #[test]
    fn class_mode_escapes_special_chars_like_single_path() {
        let h = Highlighter::new();
        let code = "let s = \"a & b < c > d ' e\";\n";
        let html = h
            .highlight_lines_classes(code, Some("rust"), "hi-", &BTreeMap::new())
            .expect("ok")
            .lines
            .concat();
        for needle in ["&amp;", "&lt;", "&gt;", "&quot;", "&#39;"] {
            assert!(
                html.contains(needle),
                "class output missing escaped {needle}: {html}"
            );
        }
        assert!(!html.contains(" & "), "raw ampersand leaked: {html}");
    }

    /// Adjacent same-class tokens merge into ONE span. A pure line comment
    /// tokenizes into several `com` regions (`//`, the words); after merging,
    /// the whole line is exactly one `<span>`.
    #[test]
    fn class_mode_merges_adjacent_same_class_tokens() {
        let h = Highlighter::new();
        let result = h
            .highlight_lines_classes("// two words here\n", Some("rust"), "hi-", &BTreeMap::new())
            .expect("ok");
        let line = &result.lines[0];
        assert_eq!(
            line.matches("<span").count(),
            1,
            "adjacent comment tokens must merge into one span: {line}"
        );
        assert!(
            line.contains("class=\"hi-com\""),
            "comment span must be hi-com: {line}"
        );
        assert!(
            line.contains("two words here"),
            "comment text preserved: {line}"
        );
    }

    /// A configured `roleClasses` override is emitted VERBATIM for its role,
    /// replacing the `{prefix}{short_name}` default; other roles keep the
    /// prefix default.
    #[test]
    fn class_mode_role_classes_override_emitted_verbatim() {
        let h = Highlighter::new();
        let mut roles = BTreeMap::new();
        // Keyed by the FULL role name, exactly as user config supplies it.
        roles.insert(
            "keyword".to_string(),
            "text-violet-600 dark:text-violet-400".to_string(),
        );
        let html = h
            .highlight_lines_classes("let x = 1;\n", Some("rust"), "hi-", &roles)
            .expect("ok")
            .lines
            .concat();
        assert!(
            html.contains("class=\"text-violet-600 dark:text-violet-400\""),
            "override class must be emitted verbatim: {html}"
        );
        assert!(
            !html.contains("class=\"hi-kw\""),
            "overridden role must not use the default class: {html}"
        );
        assert!(
            html.contains("class=\"hi-num\""),
            "non-overridden role still uses the prefix default: {html}"
        );
    }

    /// A `roleClasses` override value is attribute-escaped when emitted (the
    /// value is user-supplied, so specials like `"` / `&` must be escaped).
    #[test]
    fn class_mode_role_class_override_is_attribute_escaped() {
        let h = Highlighter::new();
        let mut roles = BTreeMap::new();
        roles.insert("keyword".to_string(), "a\"b&c".to_string());
        let html = h
            .highlight_lines_classes("let x = 1;\n", Some("rust"), "hi-", &roles)
            .expect("ok")
            .lines
            .concat();
        assert!(
            html.contains("class=\"a&quot;b&amp;c\""),
            "override must be attribute-escaped: {html}"
        );
    }

    /// An unclassified token (classifier returns `None`) is emitted as bare
    /// escaped text with NO wrapper span. Inter-token whitespace carries only
    /// the grammar-root scope, which `classify` maps to `None`, so a literal
    /// space sits unwrapped between two spans.
    #[test]
    fn class_mode_unclassified_token_has_no_span() {
        let h = Highlighter::new();
        let html = h
            .highlight_lines_classes("let x = 1;\n", Some("rust"), "hi-", &BTreeMap::new())
            .expect("ok")
            .lines
            .concat();
        assert!(
            html.contains("</span> <span"),
            "inter-token whitespace must be bare (no wrapper span): {html}"
        );
    }

    /// Unknown lang mirrors the escaped fallback: no spans, escaped source,
    /// `fallback = true`.
    #[test]
    fn class_mode_unknown_lang_falls_back_escaped_no_spans() {
        let h = Highlighter::new();
        let result = h
            .highlight_lines_classes(
                "<hello> & 'world'\n",
                Some("klingon"),
                "hi-",
                &BTreeMap::new(),
            )
            .expect("fallback ok");
        assert!(result.fallback, "unknown lang must set fallback = true");
        assert_eq!(
            result.fallback_reason,
            Some(ClassHighlightFallbackReason::UnknownLanguage),
            "unknown-language fallback must retain its typed cause"
        );
        let html = result.lines.concat();
        assert!(
            !html.contains("<span"),
            "fallback must be plain text: {html}"
        );
        assert!(
            html.contains("&lt;hello&gt;"),
            "fallback not escaped: {html}"
        );
        assert!(html.contains("&amp;"), "fallback amp not escaped: {html}");
        assert!(
            html.contains("&#39;world&#39;"),
            "fallback quote not escaped: {html}"
        );
    }
}
