# Formula for the zfb binary — auto-generated by scripts/update-homebrew-formula.sh
# Do not edit manually; regenerate with:
#   ./scripts/update-homebrew-formula.sh <version> --push
class Zfb < Formula
  desc "Rust-built static-site engine — millisecond rebuilds, single binary"
  homepage "https://takazudomodular.com/pj/zudo-front-builder/"
  # Source: GitHub Releases from Takazudo/zudo-front-builder (not the npm registry).
  # Archive contract: zfb-{semver}-{target-triple}.tar.gz, one file at archive root.
  license "MIT"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v0.1.0/zfb-0.1.0-aarch64-apple-darwin.tar.gz"
      # placeholder — will be replaced by update-homebrew-formula.sh on first real release
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end

    on_intel do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v0.1.0/zfb-0.1.0-x86_64-apple-darwin.tar.gz"
      # placeholder — will be replaced by update-homebrew-formula.sh on first real release
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v0.1.0/zfb-0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      # placeholder — will be replaced by update-homebrew-formula.sh on first real release
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end

    on_intel do
      url "https://github.com/Takazudo/zudo-front-builder/releases/download/v0.1.0/zfb-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      # placeholder — will be replaced by update-homebrew-formula.sh on first real release
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "zfb"
  end

  test do
    system bin/"zfb", "--version"
  end
end
